import {Building2,History,UsersRound,X} from 'lucide-react';
import {formatPersianDate,formatPersianDateTime} from '../PersianDate';
import {RecordDialog} from '../RecordDialog';
import type {LegalEntity,LegalEntityOfficer,LegalEntityProfileHistory} from '../legal-inspection/model';
import {LEGAL_ENTITY_FORM_LABELS,LEGAL_ENTITY_OFFICER_ROLE_LABELS} from './entityProfile';

export function LegalEntityProfileDetails({entity,officers,history,onClose}:{entity:LegalEntity;officers:LegalEntityOfficer[];history:LegalEntityProfileHistory[];onClose:()=>void}){
  const active=officers.filter((item)=>item.status==='active');
  return <RecordDialog ariaLabel={`جزئیات شخصیت حقوقی ${entity.displayName}`} className="dialog-card legal-dialog entity-profile-dialog" onClose={onClose}>
    <header><div><span>خزانه · نمای فقط‌خواندنی</span><h2>{entity.displayName}</h2><p>نسخه {entity.version.toLocaleString('fa-IR')} · اطلاعات هویتی فقط به‌صورت ماسک‌شده</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="بستن"><X size={20}/></button></header>
    <div className="entity-profile-details">
      <section className="entity-profile-section"><div className="entity-profile-section__title"><Building2 size={19}/><strong>مشخصات ثبتی و نشانی</strong></div><dl className="entity-profile-facts"><div><dt>نوع شرکت</dt><dd>{entity.legalForm?LEGAL_ENTITY_FORM_LABELS[entity.legalForm]:'ثبت نشده'}</dd></div><div><dt>شناسه ملی</dt><dd dir="ltr">{entity.nationalIdentifierMasked??'ثبت نشده'}</dd></div><div><dt>شماره ثبت</dt><dd dir="ltr">{entity.registrationNumberMasked??'ثبت نشده'}</dd></div><div><dt>تاریخ تأسیس/ثبت</dt><dd>{formatPersianDate(entity.registeredAt)}</dd></div><div><dt>کد پستی</dt><dd dir="ltr">{entity.postalCodeMasked??'ثبت نشده'}</dd></div><div className="entity-profile-facts__wide"><dt>آخرین مرکز یا نشانی</dt><dd>{entity.registeredAddress??'ثبت نشده'}</dd></div></dl></section>
      <section className="entity-profile-section"><div className="entity-profile-section__title"><UsersRound size={19}/><strong>مدیران، اعضای هیئت‌مدیره و شرکا</strong></div>{!active.length?<div className="entity-profile-empty">فرد فعالی ثبت نشده است.</div>:<div className="entity-officer-summary">{active.map((item)=><article key={item.id}><div><strong>{item.displayName}</strong><span>{LEGAL_ENTITY_OFFICER_ROLE_LABELS[item.role]}</span></div><dl><div><dt>کد ملی</dt><dd dir="ltr">{item.nationalIdMasked??'ثبت نشده'}</dd></div><div><dt>دوره مسئولیت</dt><dd>{item.unlimitedTenure?'نامحدود':`${formatPersianDate(item.appointmentStartDate)} تا ${formatPersianDate(item.appointmentEndDate)}`}</dd></div>{item.shareAmountRial&&<div><dt>سهم‌الشرکه</dt><dd>{Number(item.shareAmountRial).toLocaleString('fa-IR')} ریال</dd></div>}</dl></article>)}</div>}</section>
      <section className="entity-profile-section"><div className="entity-profile-section__title"><History size={19}/><strong>تاریخچه پروفایل</strong></div>{!history.length?<div className="entity-profile-empty">تاریخچه‌ای ثبت نشده است.</div>:<div className="record-history">{[...history].sort((a,b)=>b.sequence-a.sequence).map((item)=><article key={item.id}><span/><div><strong>{item.action==='created'?'ایجاد پروفایل':item.action==='profile_updated'?'ویرایش پروفایل':'تغییر وضعیت'} · نسخه {item.entityVersion.toLocaleString('fa-IR')}</strong><small>{formatPersianDateTime(item.occurredAt)} · {item.changedFields.length.toLocaleString('fa-IR')} فیلد · {item.officerAddedCount.toLocaleString('fa-IR')} افزوده، {item.officerUpdatedCount.toLocaleString('fa-IR')} ویرایش، {item.officerEndedCount.toLocaleString('fa-IR')} خاتمه</small></div></article>)}</div>}</section>
    </div>
  </RecordDialog>;
}
