import {describe,expect,it} from 'vitest';
import {createSeedData} from '../seed';
import type {LocalUser,SecurityRole} from '../model';
import type {CompanyBankAccountDetail,LegalEntity,BankInstitution,LegalEntityOfficer,LegalEntityProfileHistory} from '../legal-inspection/model';
import {projectTreasuryMaster} from './projection';
import {TREASURY_MASTER_PERMISSIONS,treasuryMasterRouteAllowed} from './policy';

const now='2026-08-28T00:00:00.000Z';
function fixture(scope:'COMPANY'|'SELF'='COMPANY'){
  const seed=createSeedData();const base=(seed.users as LocalUser[])[0];const permissions=[TREASURY_MASTER_PERMISSIONS.view,TREASURY_MASTER_PERMISSIONS.bankMaskedView];
  const user:LocalUser={...base,isAdmin:false,roleId:'role-ref',roleIds:['role-ref'],permissions,permissionEntitlements:permissions.map((permission)=>({permission,scope,source:'role' as const,sourceRoleId:'role-ref'}))};
  const roles:[SecurityRole]=[{id:'role-ref',name:'مرجع مالی',description:'test',status:'active',protected:false,scope,permissions,createdAt:now,updatedAt:now,version:1}];
  const entity:LegalEntity={id:'entity',tenantId:user.companyId,companyId:user.companyId,displayName:'شرکت مصنوعی',status:'active',version:1,createdAt:now,updatedAt:now};
  const bank:BankInstitution={id:'bank',tenantId:user.companyId,companyId:user.companyId,code:'QA',displayName:'بانک مصنوعی',status:'active',version:1,createdAt:now,updatedAt:now};
  const account:CompanyBankAccountDetail={id:'account',tenantId:user.companyId,companyId:user.companyId,legalEntityId:entity.id,bankInstitutionId:bank.id,iban:'IR000000000000000000000000',cardNumber:'1111222233334444',maskedIban:'**********************0000',maskedCardNumber:'************4444',last4:'4444',status:'active',version:1,createdAt:now,updatedAt:now};
  return {user,roles,entity,bank,account};
}

describe('shared treasury master projection',()=>{
  it('allows the dedicated route with only the active shared reference permission',()=>{const f=fixture();expect(f.user.permissions).not.toContain('treasury.bank-account.view');expect(treasuryMasterRouteAllowed(f.user)).toBe(true);expect(treasuryMasterRouteAllowed({...f.user,permissions:[]})).toBe(false);});
  it('projects one canonical masked reference set without raw banking values',()=>{const f=fixture();const result=projectTreasuryMaster({activeUser:f.user,roles:f.roles,legalEntities:[f.entity],legalEntityOfficers:[],legalEntityHistory:[],bankInstitutions:[f.bank],bankAccounts:[f.account]});expect(result.legalEntities).toHaveLength(1);expect(result.bankAccounts[0]).toMatchObject({last4:'4444',maskedCardNumber:'************4444'});expect(result.bankAccounts[0]).not.toHaveProperty('cardNumber');expect(JSON.stringify(result)).not.toContain('1111222233334444');});
  it('never projects a bank owned by another tenant',()=>{const f=fixture();const foreign={...f.bank,id:'foreign-bank',tenantId:'company-other',companyId:'company-other'};const result=projectTreasuryMaster({activeUser:f.user,roles:f.roles,legalEntities:[f.entity],legalEntityOfficers:[],legalEntityHistory:[],bankInstitutions:[f.bank,foreign],bankAccounts:[f.account]});expect(result.bankInstitutions.map((item)=>item.id)).toEqual([f.bank.id]);});
  it('fails closed for an account whose legacy bank ownership is unresolved',()=>{const f=fixture();const unresolved={...f.bank,tenantId:`unresolved-company:${f.bank.id}`,companyId:`unresolved-company:${f.bank.id}`};const result=projectTreasuryMaster({activeUser:f.user,roles:f.roles,legalEntities:[f.entity],legalEntityOfficers:[],legalEntityHistory:[],bankInstitutions:[unresolved],bankAccounts:[f.account]});expect(result.bankInstitutions).toEqual([]);expect(result.bankAccounts).toEqual([]);});
  it('does not widen a SELF role or system admin without an assigned active role',()=>{const f=fixture('SELF');expect(projectTreasuryMaster({activeUser:f.user,roles:f.roles,legalEntities:[f.entity],legalEntityOfficers:[],legalEntityHistory:[],bankInstitutions:[f.bank],bankAccounts:[f.account]}).legalEntities).toEqual([]);expect(projectTreasuryMaster({activeUser:{...f.user,isAdmin:true,roleIds:[]},roles:f.roles,legalEntities:[f.entity],legalEntityOfficers:[],legalEntityHistory:[],bankInstitutions:[f.bank],bankAccounts:[f.account]}).legalEntities).toEqual([]);});
  it('projects officers and sanitized profile history only with the separate active permission and exact tenant',()=>{const f=fixture();const permissions=[...f.roles[0].permissions,TREASURY_MASTER_PERMISSIONS.officerView];const role={...f.roles[0],permissions};const user={...f.user,permissions,permissionEntitlements:permissions.map((permission)=>({permission,scope:'COMPANY' as const,source:'role' as const,sourceRoleId:role.id}))};const officer:LegalEntityOfficer={id:'officer',tenantId:user.companyId,companyId:user.companyId,legalEntityId:f.entity.id,displayName:'مدیر کاملاً ساختگی',nationalIdMasked:'******0000',role:'chief_executive',status:'active',version:1,createdAt:now,updatedAt:now};const history:LegalEntityProfileHistory={id:'history',tenantId:user.companyId,companyId:user.companyId,legalEntityId:f.entity.id,sequence:1,action:'created',actorId:user.actorId,effectiveUserId:user.id,occurredAt:now,entityVersion:1,changedFields:['displayName'],officerAddedCount:1,officerUpdatedCount:0,officerEndedCount:0,correlationId:'correlation'};const foreign={...officer,id:'foreign-officer',tenantId:'other'};const result=projectTreasuryMaster({activeUser:user,roles:[role],legalEntities:[f.entity],legalEntityOfficers:[officer,foreign],legalEntityHistory:[history],bankInstitutions:[f.bank],bankAccounts:[f.account]});expect(result.legalEntityOfficers).toEqual([officer]);expect(result.legalEntityHistory).toEqual([history]);expect(projectTreasuryMaster({activeUser:f.user,roles:f.roles,legalEntities:[f.entity],legalEntityOfficers:[officer],legalEntityHistory:[history],bankInstitutions:[f.bank],bankAccounts:[f.account]}).legalEntityOfficers).toEqual([]);});
});
