import {useRef,useState,type FormEvent,type ReactNode} from 'react';
import {BadgeAlert,Eye,Landmark,Pencil,Plus,Search,ShieldCheck,X} from 'lucide-react';
import type {FoundationState} from '../model';
import type {LocalFoundationService} from '../service';
import type {FoundationExecutor} from '../OrganizationPages';
import {RecordDialog} from '../RecordDialog';
import {TREASURY_MASTER_PERMISSIONS,treasuryMasterAllowed,treasuryMasterResource} from './policy';
import {LEGAL_ENTITY_FORM_LABELS,type LegalEntityProfileInput} from './entityProfile';
import {LegalEntityProfileDialog} from './LegalEntityProfileDialog';
import {LegalEntityProfileDetails} from './LegalEntityProfileDetails';

interface Props{state:FoundationState;service:LocalFoundationService;execute:FoundationExecutor;onOpenOperations?:()=>void}
const accountMask=(account:NonNullable<FoundationState['treasuryMaster']>['bankAccounts'][number])=>account.maskedIban??account.maskedAccountNumber??account.maskedCardNumber??`****${account.last4}`;

export function TreasuryMasterDataPage({state,service,execute,onOpenOperations}:Props){
  const data=state.treasuryMaster;
  const [tab,setTab]=useState<'entities'|'banks'|'accounts'>('entities');
  const [dialog,setDialog]=useState<typeof tab|null>(null);
  const [entityDialogId,setEntityDialogId]=useState<string|undefined>();
  const [entityDetailsId,setEntityDetailsId]=useState<string|undefined>();
  const [query,setQuery]=useState('');
  const command=useRef<{id:string;fingerprint:string}|undefined>(undefined);
  if(!data)return <div className="empty-state"><ShieldCheck size={28}/><strong>اطلاعات پایه بانکی در دسترس نیست.</strong></div>;
  const aggregate=treasuryMasterResource('treasury-master',state.activeUser.companyId);
  const manage=treasuryMasterAllowed(state.activeUser,state.roles,TREASURY_MASTER_PERMISSIONS.manage,aggregate,'edit');
  const viewOfficers=treasuryMasterAllowed(state.activeUser,state.roles,TREASURY_MASTER_PERMISSIONS.officerView,aggregate,'view');
  const manageOfficers=treasuryMasterAllowed(state.activeUser,state.roles,TREASURY_MASTER_PERMISSIONS.officerManage,aggregate,'edit');
  const manageAccount=treasuryMasterAllowed(state.activeUser,state.roles,TREASURY_MASTER_PERMISSIONS.bankAccountManage,aggregate,'edit');
  const run=(kind:string,input:unknown,work:(id:string)=>Promise<FoundationState>,success:string)=>{const fingerprint=JSON.stringify({kind,input});if(!command.current||command.current.fingerprint!==fingerprint)command.current={id:`ui-treasury-master:${kind}:${crypto.randomUUID()}`,fingerprint};return execute(`treasury-master-${kind}`,()=>work(command.current!.id),success).then((ok)=>{if(ok){command.current=undefined;setDialog(null);}return ok;});};
  const entities=data.legalEntities.filter((item)=>{const people=data.legalEntityOfficers.filter((officer)=>officer.legalEntityId===item.id&&officer.status==='active').map((officer)=>officer.displayName).join(' ');return `${item.displayName} ${item.nationalIdentifierMasked??''} ${item.registrationNumberMasked??''} ${people}`.toLocaleLowerCase('fa').includes(query.toLocaleLowerCase('fa'));});
  const banks=data.bankInstitutions.filter((item)=>`${item.displayName} ${item.code}`.toLocaleLowerCase('fa').includes(query.toLocaleLowerCase('fa')));
  const accounts=data.bankAccounts.filter((item)=>{const owner=data.legalEntities.find((entry)=>entry.id===item.legalEntityId)?.displayName??'';const bank=data.bankInstitutions.find((entry)=>entry.id===item.bankInstitutionId)?.displayName??'';return `${owner} ${bank} ${item.last4}`.toLocaleLowerCase('fa').includes(query.toLocaleLowerCase('fa'));});
  const setStatus=(id:string,version:number,current:'active'|'inactive',label:string)=>run('status',{id,version,current},(commandId)=>service.setLegalRecordStatus(id,version,current==='active'?'inactive':'active','qa_lifecycle',commandId),`وضعیت ${label} تغییر کرد.`);
  return <div className="page-stack treasury-master-page">
    <section className="page-intro"><div className="page-intro__icon"><Landmark size={24}/></div><div><span className="eyebrow">خزانه · منبع مشترک</span><h2>اطلاعات پایه شرکت‌ها و بانک‌ها</h2><p>مرجع واحد شخصیت‌های حقوقی، مدیران و اعضا، بانک‌ها و حساب‌های بانکی برای خزانه، حقوقی و سایر واحدهای مجاز.</p></div><div className="erp-intro__actions"><span className="scope-badge">فقط داده آزمایشی</span>{onOpenOperations&&<button className="button button--secondary" onClick={onOpenOperations}>صف پرداخت خزانه</button>}</div></section>
    <div className="legal-prototype-banner"><BadgeAlert size={20}/><div><strong>ورود اطلاعات واقعی ممنوع است</strong><span>مقادیر حساب در همه فهرست‌ها ماسک می‌شوند و ماژول قدیمی حساب بانکی دیگر قابل تغییر نیست.</span></div></div>
    <div className="module-tabs" role="tablist" aria-label="اطلاعات پایه بانکی">{([['entities','شخصیت‌های حقوقی',data.legalEntities.length],['banks','بانک‌ها',data.bankInstitutions.length],['accounts','حساب‌های بانکی',data.bankAccounts.length]] as const).map(([id,label,count])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}><strong>{label}</strong><span>{count.toLocaleString('fa-IR')}</span></button>)}</div>
    <section className="panel operational-list"><div className="operational-toolbar"><div><span className="eyebrow">مرجع مشترک خزانه</span><h3>{tab==='entities'?'شخصیت‌های حقوقی':tab==='banks'?'بانک‌ها':'حساب‌های بانکی'}</h3></div><div className="operational-filters"><label className="search-field"><Search size={17}/><input aria-label="جست‌وجوی اطلاعات پایه" value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="جست‌وجوی نام، کد یا چهار رقم آخر…"/></label>{((tab==='accounts'&&manageAccount)||(tab==='banks'&&manage)||(tab==='entities'&&manage&&manageOfficers))&&<button className="button button--primary" onClick={()=>{command.current=undefined;setDialog(tab)}}><Plus size={18}/>{tab==='entities'?'ثبت شخصیت حقوقی':tab==='banks'?'ثبت بانک':'ثبت حساب بانکی'}</button>}</div></div>
      {tab==='entities'&&<MasterTable headers={['نام شرکت','نوع شرکت','شناسه ملی','شماره ثبت','مدیرعامل','اعضای فعال','وضعیت','نسخه','اقدام']}>{entities.map((item)=>{const officers=data.legalEntityOfficers.filter((officer)=>officer.legalEntityId===item.id&&officer.status==='active');const ceo=officers.find((officer)=>officer.role==='chief_executive');const incomplete=!item.legalForm||(!item.nationalIdentifierMasked&&!item.registrationNumberMasked)||!item.registeredAt||!item.registeredAddress;return <tr key={item.id}><td><strong>{item.displayName}</strong>{item.qaDatasetId&&<small className="qa-label">دیتاست QA</small>}{incomplete&&<small className="entity-profile-incomplete">پروفایل نیازمند تکمیل</small>}</td><td>{item.legalForm?LEGAL_ENTITY_FORM_LABELS[item.legalForm]:'ثبت نشده'}</td><td><code dir="ltr">{item.nationalIdentifierMasked??'ثبت نشده'}</code></td><td><code dir="ltr">{item.registrationNumberMasked??'ثبت نشده'}</code></td><td>{viewOfficers?(ceo?.displayName??'ثبت نشده'):'محدود'}</td><td>{viewOfficers?officers.length.toLocaleString('fa-IR'):'—'}</td><td><Status value={item.status}/></td><td>{item.version.toLocaleString('fa-IR')}</td><td><div className="table-actions">{viewOfficers&&<button className="button button--secondary" onClick={()=>setEntityDetailsId(item.id)}><Eye size={15}/>مشاهده جزئیات</button>}{manage&&viewOfficers&&manageOfficers&&!item.qaDatasetId&&<button className="button button--secondary" onClick={()=>{command.current=undefined;setEntityDialogId(item.id)}}><Pencil size={15}/>ویرایش</button>}{manage&&<button className="button button--secondary" onClick={()=>void setStatus(item.id,item.version,item.status,item.displayName)}>{item.status==='active'?'غیرفعال‌سازی':'فعال‌سازی'}</button>}</div></td></tr>})}</MasterTable>}
      {tab==='banks'&&<MasterTable headers={['بانک','کد','تعداد حساب','وضعیت','آخرین تغییر','اقدام']}>{banks.map((item)=><tr key={item.id}><td><strong>{item.displayName}</strong>{item.qaDatasetId&&<small className="qa-label">دیتاست QA</small>}</td><td><code dir="ltr">{item.code}</code></td><td>{data.bankAccounts.filter((account)=>account.bankInstitutionId===item.id).length.toLocaleString('fa-IR')}</td><td><Status value={item.status}/></td><td>نسخه {item.version.toLocaleString('fa-IR')}</td><td>{manage&&<button className="button button--secondary" onClick={()=>void setStatus(item.id,item.version,item.status,item.displayName)}>{item.status==='active'?'غیرفعال‌سازی':'فعال‌سازی'}</button>}</td></tr>)}</MasterTable>}
      {tab==='accounts'&&<MasterTable headers={['شخصیت مالک','بانک','حساب ماسک‌شده','چهار رقم آخر','وضعیت','نسخه','اقدام']}>{accounts.map((item)=>{const owner=data.legalEntities.find((entry)=>entry.id===item.legalEntityId);const bank=data.bankInstitutions.find((entry)=>entry.id===item.bankInstitutionId);return <tr key={item.id}><td><strong>{owner?.displayName??'نامشخص'}</strong></td><td>{bank?.displayName??'نامشخص'}</td><td><code dir="ltr">{accountMask(item)}</code>{item.qaDatasetId&&<small className="qa-label">دیتاست QA</small>}</td><td><code dir="ltr">{item.last4}</code></td><td><Status value={item.status}/></td><td>{item.version.toLocaleString('fa-IR')}</td><td>{manageAccount&&<button className="button button--secondary" onClick={()=>void setStatus(item.id,item.version,item.status,`حساب ${item.last4}`)}>{item.status==='active'?'غیرفعال‌سازی':'فعال‌سازی'}</button>}</td></tr>})}</MasterTable>}
    </section>
    {dialog==='entities'&&<LegalEntityProfileDialog officers={[]} onClose={()=>setDialog(null)} onSubmit={(values)=>run('entity-create',values,(id)=>service.createLegalEntity(values,id),'شخصیت حقوقی در مرجع خزانه ثبت شد.')}/>} 
    {entityDialogId&&(()=>{const entity=data.legalEntities.find((item)=>item.id===entityDialogId);if(!entity)return null;const officers=data.legalEntityOfficers.filter((item)=>item.legalEntityId===entity.id);return <LegalEntityProfileDialog entity={entity} officers={officers} onClose={()=>setEntityDialogId(undefined)} onSubmit={(values:LegalEntityProfileInput)=>run('entity-update',{id:entity.id,version:entity.version,values},(commandId)=>service.updateLegalEntity(entity.id,entity.version,values,commandId),'اطلاعات شخصیت حقوقی و مدیران به‌روزرسانی شد.').then((ok)=>{if(ok)setEntityDialogId(undefined);return ok;})}/>})()}
    {entityDetailsId&&(()=>{const entity=data.legalEntities.find((item)=>item.id===entityDetailsId);if(!entity)return null;return <LegalEntityProfileDetails entity={entity} officers={data.legalEntityOfficers.filter((item)=>item.legalEntityId===entity.id)} history={data.legalEntityHistory.filter((item)=>item.legalEntityId===entity.id)} onClose={()=>setEntityDetailsId(undefined)}/>})()}
    {dialog==='banks'&&<SimpleDialog title="ثبت بانک آزمایشی" fields={[['code','کد بانک'],['displayName','نام بانک']]} onClose={()=>setDialog(null)} onSubmit={(values)=>run('bank',values,(id)=>service.createLegalBankInstitution(values as {code:string;displayName:string},id),'بانک در مرجع خزانه ثبت شد.')}/>} 
    {dialog==='accounts'&&<AccountDialog state={state} onClose={()=>setDialog(null)} onSubmit={(values)=>run('account',values,(id)=>service.createLegalBankAccount(values,id),'حساب در مرجع خزانه ثبت و ماسک شد.')}/>} 
  </div>;
}

function MasterTable({headers,children}:{headers:string[];children:ReactNode}){return <div className="operational-table-wrap" tabIndex={0} aria-label="جدول اطلاعات پایه خزانه؛ برای مشاهده ستون‌های بیشتر پیمایش کنید"><table className="operational-table"><thead><tr><th>ردیف</th>{headers.map((item)=><th key={item}>{item}</th>)}</tr></thead><tbody>{Array.isArray(children)?children.map((row,index)=><RowNumber key={index} index={index}>{row}</RowNumber>):children}</tbody></table></div>}
function RowNumber({index,children}:{index:number;children:ReactNode}){if(!children||typeof children!=='object'||!('props' in children))return <>{children}</>;const row=children as React.ReactElement<{children:ReactNode}>;return <tr><td className="operational-row-number">{(index+1).toLocaleString('fa-IR')}</td>{row.props.children}</tr>}
function Status({value}:{value:'active'|'inactive'}){return <span className={`state-badge state-badge--${value==='active'?'good':'neutral'}`}>{value==='active'?'فعال':'غیرفعال'}</span>}
function Shell({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}){return <RecordDialog ariaLabel={title} className="dialog-card legal-dialog" onClose={onClose}><header><div><span>اطلاعات پایه خزانه</span><h2>{title}</h2></div><button type="button" className="icon-button" onClick={onClose} aria-label="بستن"><X size={20}/></button></header><div className="legal-prototype-inline"><BadgeAlert size={18}/>فقط اطلاعات ساختگی وارد کنید.</div>{children}</RecordDialog>}
function SimpleDialog({title,fields,onClose,onSubmit}:{title:string;fields:Array<[string,string]>;onClose:()=>void;onSubmit:(value:Record<string,string>)=>void}){const [values,setValues]=useState<Record<string,string>>({});return <Shell title={title} onClose={onClose}><form onSubmit={(event)=>{event.preventDefault();onSubmit(values)}}><div className="form-grid">{fields.map(([name,label])=><label key={name}>{label}<input required value={values[name]??''} onChange={(event)=>setValues({...values,[name]:event.target.value})}/></label>)}</div><footer><button type="button" className="button button--secondary" onClick={onClose}>انصراف</button><button className="button button--primary">ثبت</button></footer></form></Shell>}
function AccountDialog({state,onClose,onSubmit}:{state:FoundationState;onClose:()=>void;onSubmit:(input:{legalEntityId:string;bankInstitutionId:string;iban?:string;cardNumber?:string;accountNumber?:string})=>void}){const data=state.treasuryMaster!;const entities=data.legalEntities.filter((item)=>item.status==='active'&&!item.qaDatasetId);const banks=data.bankInstitutions.filter((item)=>item.status==='active'&&!item.qaDatasetId);const [legalEntityId,setEntity]=useState(entities[0]?.id??'');const [bankInstitutionId,setBank]=useState(banks[0]?.id??'');const [iban,setIban]=useState('');const [cardNumber,setCard]=useState('');const submit=(event:FormEvent)=>{event.preventDefault();onSubmit({legalEntityId,bankInstitutionId,iban,cardNumber})};return <Shell title="ثبت حساب بانکی آزمایشی" onClose={onClose}><form onSubmit={submit}><div className="form-grid"><label>شخصیت حقوقی<select required value={legalEntityId} onChange={(event)=>setEntity(event.target.value)}>{entities.map((item)=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label>بانک<select required value={bankInstitutionId} onChange={(event)=>setBank(event.target.value)}>{banks.map((item)=><option key={item.id} value={item.id}>{item.displayName}</option>)}</select></label><label>شبای ساختگی<input dir="ltr" value={iban} onChange={(event)=>setIban(event.target.value)}/></label><label>کارت ساختگی<input dir="ltr" value={cardNumber} onChange={(event)=>setCard(event.target.value)}/></label></div><footer><button type="button" className="button button--secondary" onClick={onClose}>انصراف</button><button className="button button--primary">ثبت و ماسک‌سازی</button></footer></form></Shell>}
