import {useMemo, useState} from 'react';
import {Building2, GitBranch, MapPin, Pencil, Plus, Power, Search, UserRound, X} from 'lucide-react';
import {can} from './authorization';
import {FormValidationSummary, OptionalLabel, RequiredLabel, validateRequired} from './FormValidation';
import {SortHeader, useSortableRows, type SortColumn} from './Sorting';
import type {FoundationState, OrganizationalUnit} from './model';
import type {LocalFoundationService, UnitInput} from './service';

interface Props {
  state: FoundationState;
  service: LocalFoundationService;
  execute: (label: string, work: () => Promise<FoundationState>, success: string) => Promise<void>;
}

export function BranchesPage({state, service, execute}: Props) {
  const [query, setQuery] = useState('');
  const [editing, setEditing] = useState<OrganizationalUnit | 'new' | null>(null);
  const [statusTarget, setStatusTarget] = useState<OrganizationalUnit | null>(null);
  const branches = state.units.filter((unit) => unit.type.trim() === 'شعبه');
  const branchMemberCount = (branchId: string) => state.personnel.filter((person)=>person.branchUnitId===branchId).length+state.users.filter((user)=>!user.personnelId&&user.branchUnitId===branchId).length;
  const visible = useMemo(() => branches.filter((branch) => {const manager=state.users.find((user)=>user.id===branch.managerUserId);const parent=state.units.find((unit)=>unit.id===branch.parentId);return `${branch.name} ${branch.description} ${manager?.name??''} ${parent?.name??''} ${branch.status==='active'?'فعال':'غیرفعال'}`.toLocaleLowerCase('fa').includes(query.trim().toLocaleLowerCase('fa'));}), [branches, state.users, state.units, query]);
  const branchSortColumns = useMemo<SortColumn<OrganizationalUnit>[]>(() => [
    {key:'name',kind:'text',value:(branch)=>branch.name},
    {key:'manager',kind:'text',value:(branch)=>state.users.find((user)=>user.id===branch.managerUserId)?.name},
    {key:'parent',kind:'text',value:(branch)=>state.units.find((unit)=>unit.id===branch.parentId)?.name},
    {key:'members',kind:'number',value:(branch)=>branchMemberCount(branch.id)},
    {key:'status',kind:'text',value:(branch)=>branch.status==='active'?'فعال':'غیرفعال'},
  ], [state.personnel, state.users, state.units]);
  const {sortedRows: sortedBranches, sort: branchSort, requestSort: requestBranchSort} = useSortableRows(visible, branchSortColumns, 'name', 'asc');
  const mayManage = can(state.activeUser, 'organization.units.manage');
  return <div className="page-stack branches-page">
    <section className="page-intro org-page-intro"><span className="page-intro-icon"><Building2 size={24}/></span><div><span>سازمان / شعبه</span><h2>شعبه‌های شرکت</h2><p>شعبه‌ها جدا از واحدها و تیم‌های داخلی نمایش داده می‌شوند، اما همچنان بخشی از ساختار رسمی سازمان هستند.</p></div>{mayManage&&<div className="page-intro-action"><button className="org-primary-action" onClick={()=>setEditing('new')}><Plus size={18}/> شعبه جدید</button></div>}</section>
    <section className="org-metrics"><BranchMetric value={branches.length} label="کل شعبه‌ها"/><BranchMetric value={branches.filter((item)=>item.status==='active').length} label="شعبه فعال"/><BranchMetric value={state.personnel.filter((person)=>branches.some((branch)=>branch.id===person.branchUnitId)).length+state.users.filter((user)=>!user.personnelId&&branches.some((branch)=>branch.id===user.branchUnitId)).length} label="پرسنل مستقر"/></section>
    <section className="org-panel"><div className="branch-toolbar"><label className="search-box"><Search size={18}/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="جست‌وجوی نام، مسئول، بالادست، وضعیت یا توضیحات شعبه"/></label><div className="compact-sort-bar" aria-label="مرتب‌سازی شعبه‌ها"><SortHeader columnKey="name" label="نام" sort={branchSort} onSort={requestBranchSort}/><SortHeader columnKey="manager" label="مسئول" sort={branchSort} onSort={requestBranchSort}/><SortHeader columnKey="parent" label="بالادست" sort={branchSort} onSort={requestBranchSort}/><SortHeader columnKey="members" label="پرسنل" sort={branchSort} onSort={requestBranchSort}/><SortHeader columnKey="status" label="وضعیت" sort={branchSort} onSort={requestBranchSort}/></div></div><div className="branch-grid">{sortedBranches.map((branch)=>{const manager=state.users.find((user)=>user.id===branch.managerUserId);const parent=state.units.find((unit)=>unit.id===branch.parentId);const members=branchMemberCount(branch.id);return <article className="branch-card" key={branch.id}><div className="branch-card__top"><span><Building2 size={21}/></span><i className={`status-badge status-badge--${branch.status}`}>{branch.status==='active'?'فعال':'غیرفعال'}</i></div><h3>{branch.name}</h3><p>{branch.description||'توضیحی برای این شعبه ثبت نشده است.'}</p><div className="branch-facts"><span><GitBranch size={16}/><b>بالادست</b><strong>{parent?.name??'مدیریت شرکت'}</strong></span><span><UserRound size={16}/><b>مسئول</b><strong>{manager?.name??'تعیین نشده'}</strong></span><span><MapPin size={16}/><b>پرسنل مستقر</b><strong>{members.toLocaleString('en-US')} نفر</strong></span></div>{mayManage&&<div className="icon-actions branch-actions"><button className="icon-button" aria-label="ویرایش شعبه" title="ویرایش شعبه" onClick={()=>setEditing(branch)}><Pencil size={17}/></button><button className={`icon-button ${branch.status==='active'?'icon-button--danger':'icon-button--success'}`} aria-label={branch.status==='active'?'غیرفعال‌سازی شعبه':'فعال‌سازی شعبه'} title={branch.status==='active'?'غیرفعال‌سازی شعبه':'فعال‌سازی شعبه'} onClick={()=>branch.status==='active'?setStatusTarget(branch):void execute('branch-status',()=>service.setUnitStatus(branch.id,'active'),'شعبه فعال شد.')}><Power size={17}/></button></div>}</article>})}{!sortedBranches.length&&<div className="empty-state branch-empty"><Building2 size={30}/><strong>شعبه‌ای با این جست‌وجو پیدا نشد.</strong><span>عبارت جست‌وجو را تغییر دهید یا شعبه جدید ایجاد کنید.</span></div>}</div></section>
    {editing&&<BranchDialog branch={editing==='new'?undefined:editing} state={state} onClose={()=>setEditing(null)} onSubmit={(input)=>execute('branch-save',()=>editing==='new'?service.createUnit(input):service.updateUnit(editing.id,input),editing==='new'?'شعبه جدید ایجاد شد.':'تغییرات شعبه ذخیره شد.').then(()=>setEditing(null))}/>} 
    {statusTarget&&<BranchStatusDialog branch={statusTarget} onClose={()=>setStatusTarget(null)} onConfirm={()=>execute('branch-status',()=>service.setUnitStatus(statusTarget.id,'inactive'),'شعبه غیرفعال شد.').then(()=>setStatusTarget(null))}/>} 
  </div>;
}

function BranchDialog({branch,state,onClose,onSubmit}:{branch?:OrganizationalUnit;state:FoundationState;onClose:()=>void;onSubmit:(input:UnitInput)=>Promise<void>}){const [name,setName]=useState(branch?.name??'');const [parentId,setParentId]=useState(branch?.parentId??'unit-management');const [managerUserId,setManager]=useState(branch?.managerUserId??'');const [description,setDescription]=useState(branch?.description??'');const [errors,setErrors]=useState<string[]>([]);function submit(){const next=validateRequired([{label:'نام شعبه',value:name},{label:'واحد بالادست',value:parentId}]);setErrors(next);if(next.length)return;void onSubmit({name,type:'شعبه',parentId,managerUserId:managerUserId||undefined,description});}return <div className="modal-scrim"><div className="dialog"><header><div><span className="eyebrow">اطلاعات شعبه</span><h2>{branch?'ویرایش شعبه':'ایجاد شعبه جدید'}</h2></div><button className="icon-button" onClick={onClose} aria-label="بستن"><X size={20}/></button></header><div className="dialog-body form-grid"><FormValidationSummary errors={errors}/><label className="field field--wide"><RequiredLabel>نام شعبه</RequiredLabel><input aria-required="true" value={name} onChange={(event)=>setName(event.target.value)} autoFocus/></label><label className="field"><RequiredLabel>واحد بالادست</RequiredLabel><select aria-required="true" value={parentId} onChange={(event)=>setParentId(event.target.value)}><option value="">انتخاب کنید</option>{state.units.filter((item)=>item.id!==branch?.id&&item.status==='active'&&item.type!=='شعبه').map((unit)=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><label className="field"><OptionalLabel>مسئول شعبه</OptionalLabel><select value={managerUserId} onChange={(event)=>setManager(event.target.value)}><option value="">تعیین نشده</option>{state.users.filter((item)=>item.status==='active').map((user)=><option key={user.id} value={user.id}>{user.name}</option>)}</select></label><label className="field field--wide"><OptionalLabel>توضیحات</OptionalLabel><textarea rows={4} value={description} onChange={(event)=>setDescription(event.target.value)}/></label></div><footer><button className="button button--ghost" onClick={onClose}>انصراف</button><button className="button button--primary" onClick={submit}>{branch?'ذخیره تغییرات':'ایجاد شعبه'}</button></footer></div></div>}
function BranchStatusDialog({branch,onClose,onConfirm}:{branch:OrganizationalUnit;onClose:()=>void;onConfirm:()=>void}){return <div className="modal-scrim"><div className="dialog"><header><div><span className="eyebrow">تغییر وضعیت</span><h2>غیرفعال‌سازی «{branch.name}»</h2></div><button className="icon-button" onClick={onClose}><X size={20}/></button></header><div className="dialog-body"><p className="record-description">این عملیات فقط وقتی انجام می‌شود که پرسنل فعال در شعبه مستقر نباشد. ابتدا انتقال شعبه آن‌ها را ثبت کنید؛ اطلاعات و سوابق قبلی حذف نمی‌شوند.</p></div><footer><button className="button button--ghost" onClick={onClose}>انصراف</button><button className="button button--danger" onClick={onConfirm}>تأیید غیرفعال‌سازی</button></footer></div></div>}
function BranchMetric({value,label}:{value:number;label:string}){return <article><span><Building2 size={19}/></span><div><strong>{value.toLocaleString('en-US')}</strong><b>{label}</b><small>در ساختار تک‌شرکتی</small></div></article>}
