import {useMemo, useState, type ChangeEvent, type ReactNode} from 'react';
import {Building2, CircleAlert, FileUp, Link2, MapPin, Merge, MoreVertical, Pencil, Phone, Plus, Power, Search, Sparkles, UserRound, UsersRound, X} from 'lucide-react';
import {can} from './authorization';
import {FormValidationSummary, OptionalLabel, RequiredLabel, validateRequired} from './FormValidation';
import {SortHeader, useSortableRows, type SortColumn} from './Sorting';
import type {CustomerAddress, CustomerPhone, CustomerRecord, CustomerRelationship, CustomerStatus, FoundationState} from './model';
import {findDuplicateCustomers, type CustomerImportRow, type CustomerInput, type LocalFoundationService} from './service';
import type {FoundationExecutor} from './OrganizationPages';
import {formatPersianDateTime} from './PersianDate';
import {digitsOnly, normalizePostalCode} from '../utils/operationalFormat';

interface Props {state: FoundationState; service: LocalFoundationService; execute: FoundationExecutor;}
type CustomerTab = 'summary' | 'identity' | 'contact' | 'relationships' | 'timeline' | 'notes' | 'duplicates';

export function CustomersPage({state, service, execute}: Props) {
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [type, setType] = useState('all'); const [owner, setOwner] = useState('all');
  const [selected, setSelected] = useState<CustomerRecord | null>(null); const [editing, setEditing] = useState<CustomerRecord | 'new' | null>(null); const [importOpen, setImportOpen] = useState(false); const [statusTarget, setStatusTarget] = useState<CustomerRecord | null>(null);
  const activeCustomers = state.customers.filter((item) => !item.mergedIntoCustomerId);
  const visible = useMemo(() => activeCustomers.filter((item) => `${item.displayName} ${item.nationalId ?? ''} ${item.businessId ?? ''} ${item.phones.map((phone) => phone.number).join(' ')}`.toLocaleLowerCase('fa').includes(query.trim().toLocaleLowerCase('fa')) && (status === 'all' || item.status === status) && (type === 'all' || item.type === type) && (owner === 'all' || item.ownerPersonnelId === owner)), [activeCustomers, query, status, type, owner]);
  const sortColumns = useMemo<SortColumn<CustomerRecord>[]>(() => [
    {key: 'customer', kind: 'text', value: (item) => item.displayName},
    {key: 'contact', kind: 'text', value: (item) => item.phones.find((phone) => phone.primary)?.number ?? item.phones[0]?.number},
    {key: 'owner', kind: 'text', value: (item) => {const person = state.personnel.find((row) => row.id === item.ownerPersonnelId); return person ? `${person.firstName} ${person.lastName}` : undefined;}},
    {key: 'source', kind: 'text', value: (item) => item.source},
    {key: 'status', kind: 'text', value: (item) => statusLabel(item.status)},
  ], [state.personnel]);
  const {sortedRows: sortedCustomers, sort, requestSort} = useSortableRows(visible, sortColumns, 'customer', 'asc');
  const duplicateCount = activeCustomers.filter((item, index) => findDuplicateCustomers(activeCustomers.slice(0, index), item).length > 0).length;
  return <div className="page-stack customer-page">
    <section className="page-intro org-page-intro"><span className="page-intro-icon"><UsersRound size={24} /></span><div><span>مشتری و CRM / مشتریان</span><h2>مشتریان</h2><p>هویت، راه‌های تماس، مالک پرونده، منبع و تاریخچه هر مشتری در یک نمای ۳۶۰ درجه محلی و قابل ممیزی نگهداری می‌شود.</p></div><div className="page-intro-action action-cluster">{can(state.activeUser, 'crm.customers.import') && <button className="button button--secondary" onClick={() => setImportOpen(true)}><FileUp size={18} /> ورود CSV</button>}{can(state.activeUser, 'crm.customers.create') && <button className="org-primary-action" onClick={() => setEditing('new')}><Plus size={18} /> مشتری جدید</button>}</div></section>
    <section className="org-metrics customer-metrics"><Metric value={activeCustomers.length} label="کل مشتریان" /><Metric value={activeCustomers.filter((item) => item.status === 'active').length} label="فعال" /><Metric value={activeCustomers.filter((item) => item.type === 'legal').length} label="شخص حقوقی" /><Metric value={duplicateCount} label="نیازمند بررسی تکراری" warn={duplicateCount > 0} /></section>
    <section className="org-panel customer-list-panel"><div className="customer-toolbar"><label className="search-box"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="جست‌وجوی نام، شناسه یا تلفن" /></label><select aria-label="وضعیت مشتری" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">همه وضعیت‌ها</option><option value="active">فعال</option><option value="prospect">بالقوه</option><option value="inactive">غیرفعال</option></select><select aria-label="نوع مشتری" value={type} onChange={(e) => setType(e.target.value)}><option value="all">همه انواع</option><option value="individual">حقیقی</option><option value="legal">حقوقی</option></select><select aria-label="مالک پرونده" value={owner} onChange={(e) => setOwner(e.target.value)}><option value="all">همه مالکان</option>{state.personnel.filter((item) => item.employmentStatus === 'active').map((item) => <option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</select></div>
      <div className="enterprise-table customer-table"><div className="enterprise-table-head"><span><SortHeader columnKey="customer" label="مشتری" sort={sort} onSort={requestSort}/></span><span><SortHeader columnKey="contact" label="راه تماس" sort={sort} onSort={requestSort}/></span><span><SortHeader columnKey="owner" label="مالک پرونده" sort={sort} onSort={requestSort}/></span><span><SortHeader columnKey="source" label="منبع" sort={sort} onSort={requestSort}/></span><span><SortHeader columnKey="status" label="وضعیت" sort={sort} onSort={requestSort}/></span><span>اقدام‌ها</span></div>{sortedCustomers.map((customer) => {const ownerPerson = state.personnel.find((item) => item.id === customer.ownerPersonnelId); const duplicates = findDuplicateCustomers(activeCustomers, customer, customer.id); return <article key={customer.id} className="enterprise-table-row"><button className="record-identity" onClick={() => setSelected(customer)}><span className="record-avatar">{customer.type === 'legal' ? <Building2 size={19} /> : <UserRound size={19} />}</span><span><strong>{customer.displayName}</strong><small>{customer.type === 'legal' ? 'شخص حقوقی' : 'شخص حقیقی'}{duplicates.length ? ` · ${duplicates.length.toLocaleString('en-US')} مشابه` : ''}</small></span></button><span><b>{customer.phones.find((item) => item.primary)?.number ?? customer.phones[0]?.number ?? '—'}</b><small>{customer.email ?? 'بدون ایمیل'}</small></span><span>{ownerPerson ? <><b>{ownerPerson.firstName} {ownerPerson.lastName}</b><small>{state.units.find((item) => item.id === ownerPerson.unitId)?.name}</small></> : <small>تعیین نشده</small>}</span><span>{customer.source}</span><span><i className={`status-badge status-badge--${customer.status}`}>{statusLabel(customer.status)}</i></span><div className="user-actions">{can(state.activeUser, 'crm.customers.edit') && <Icon label="ویرایش مشتری" tone="primary" onClick={() => setEditing(customer)}><Pencil size={17} /></Icon>}{can(state.activeUser, 'crm.customers.status.manage') && <Icon label={customer.status === 'inactive' ? 'فعال‌سازی مشتری' : 'غیرفعال‌سازی مشتری'} tone={customer.status === 'inactive' ? 'success' : 'danger'} onClick={() => setStatusTarget(customer)}><Power size={17} /></Icon>}<Icon label="اقدام‌های بیشتر" onClick={() => setSelected(customer)}><MoreVertical size={17} /></Icon></div></article>;})}{!sortedCustomers.length && <div className="table-empty"><Search size={22} /><strong>مشتری‌ای پیدا نشد</strong><span>فیلتر یا عبارت جست‌وجو را تغییر دهید.</span></div>}</div>
    </section>
    {selected && <Customer360 customer={state.customers.find((item) => item.id === selected.id) ?? selected} state={state} onClose={() => setSelected(null)} onEdit={() => {setEditing(selected); setSelected(null);}} onMerge={(duplicateId) => execute('customer-merge', () => service.mergeCustomers(selected.id, duplicateId), 'پرونده تکراری با حفظ تاریخچه ادغام شد.').then(() => setSelected(null))} />}
    {editing && <CustomerDialog customer={editing === 'new' ? undefined : editing} state={state} onClose={() => setEditing(null)} onSubmit={(input) => execute('customer-save', () => editing === 'new' ? service.createCustomer(input) : service.updateCustomer(editing.id, input), editing === 'new' ? 'مشتری ایجاد شد.' : 'پرونده مشتری به‌روزرسانی شد.').then(() => setEditing(null))} />}
    {importOpen && <ImportDialog state={state} onClose={() => setImportOpen(false)} onImport={(rows, name) => execute('customer-import', () => service.importCustomers(rows, name), 'ورود مشتریان پایان یافت؛ نتیجه در تاریخچه ثبت شد.').then(() => setImportOpen(false))} />}
    {statusTarget && <ConfirmDialog title={statusTarget.status === 'inactive' ? 'فعال‌سازی مشتری' : 'غیرفعال‌سازی مشتری'} text={`وضعیت پرونده «${statusTarget.displayName}» تغییر می‌کند و تاریخچه آن حفظ خواهد شد.`} confirm={statusTarget.status === 'inactive' ? 'فعال‌سازی' : 'تأیید غیرفعال‌سازی'} danger={statusTarget.status !== 'inactive'} onClose={() => setStatusTarget(null)} onConfirm={() => execute('customer-status', () => service.setCustomerStatus(statusTarget.id, statusTarget.status === 'inactive' ? 'active' : 'inactive'), 'وضعیت مشتری تغییر کرد.').then(() => setStatusTarget(null))} />}
  </div>;
}

function Customer360({customer, state, onClose, onEdit, onMerge}: {customer: CustomerRecord; state: FoundationState; onClose: () => void; onEdit: () => void; onMerge: (duplicateId: string) => void}) {
  const [tab, setTab] = useState<CustomerTab>('summary'); const [mergeTarget, setMergeTarget] = useState<CustomerRecord | null>(null); const owner = state.personnel.find((item) => item.id === customer.ownerPersonnelId); const duplicates = findDuplicateCustomers(state.customers, customer, customer.id);
  const tabs: {id: CustomerTab; label: string}[] = [{id: 'summary', label: 'خلاصه'}, {id: 'identity', label: 'هویت'}, {id: 'contact', label: 'تماس و نشانی'}, {id: 'relationships', label: 'ارتباط‌ها'}, {id: 'timeline', label: 'فعالیت‌ها'}, {id: 'notes', label: 'یادداشت‌ها'}, {id: 'duplicates', label: `تکراری‌ها${duplicates.length ? ` (${duplicates.length.toLocaleString('en-US')})` : ''}`}];
  return <Modal onClose={onClose} wide><Heading eyebrow="نمای ۳۶۰ مشتری" title={customer.displayName} text={`${customer.type === 'legal' ? 'شخص حقوقی' : 'شخص حقیقی'} · ${statusLabel(customer.status)} · منبع: ${customer.source}`} onClose={onClose} action={can(state.activeUser, 'crm.customers.edit') ? <Icon label="ویرایش پرونده مشتری" tone="primary" onClick={onEdit}><Pencil size={17} /></Icon> : undefined} /><div className="record-tabs">{tabs.map((item) => <button key={item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id)}>{item.label}</button>)}</div><div className="record-tab-body customer-360-body">
    {tab === 'summary' && <div className="summary-grid"><Summary icon={<Phone size={19} />} title="تماس اصلی" value={customer.phones.find((item) => item.primary)?.number ?? customer.phones[0]?.number ?? 'ثبت نشده'} /><Summary icon={<MapPin size={19} />} title="نشانی اصلی" value={customer.addresses.find((item) => item.primary)?.address ?? customer.addresses[0]?.address ?? 'ثبت نشده'} /><Summary icon={<UserRound size={19} />} title="مالک پرونده" value={owner ? `${owner.firstName} ${owner.lastName}` : 'تعیین نشده'} /><Summary icon={<Sparkles size={19} />} title="منشأ داده" value={customer.provenance} /></div>}
    {tab === 'identity' && <div className="detail-list"><Detail label="نام نمایشی" value={customer.displayName} /><Detail label={customer.type === 'legal' ? 'شناسه ملی' : 'کد ملی'} value={customer.type === 'legal' ? customer.businessId : customer.nationalId} /><Detail label="کد اقتصادی" value={customer.economicCode} /><Detail label="وضعیت" value={statusLabel(customer.status)} /><Detail label="تاریخ ثبت" value={formatPersianDateTime(customer.createdAt)} /></div>}
    {tab === 'contact' && <div className="contact-section"><h3>شماره‌های تماس</h3>{customer.phones.map((phone) => <article key={phone.id}><Phone size={17} /><span><strong>{phone.number}</strong><small>{phone.label}{phone.primary ? ' · اصلی' : ''}</small></span></article>)}<h3>نشانی‌ها</h3>{customer.addresses.map((address) => <article key={address.id}><MapPin size={17} /><span><strong>{address.label}{address.primary ? ' · اصلی' : ''}</strong><small>{[address.province, address.city, address.address, address.postalCode].filter(Boolean).join('، ')}</small></span></article>)}</div>}
    {tab === 'relationships' && <div className="contact-section">{customer.relationships.map((relation) => <article key={relation.id}><Link2 size={17} /><span><strong>{relation.title}</strong><small>{relation.personName ?? state.customers.find((item) => item.id === relation.relatedCustomerId)?.displayName ?? '—'} · {relation.description}</small></span></article>)}{!customer.relationships.length && <Empty text="ارتباطی برای این مشتری ثبت نشده است." />}</div>}
    {tab === 'timeline' && <div className="record-history">{[...customer.timeline].reverse().map((item) => <article key={item.id}><span /><div><strong>{item.title}</strong><small>{item.actorName} · {formatPersianDateTime(item.occurredAt)}</small>{item.description && <p>{item.description}</p>}</div></article>)}</div>}
    {tab === 'notes' && <div className="notes-panel">{customer.notes || 'یادداشتی ثبت نشده است.'}</div>}
    {tab === 'duplicates' && <div className="duplicate-review"><div className="sensitive-note"><CircleAlert size={20} /><span><strong>ادغام کنترل‌شده</strong> سیستم فقط مشابهت امن را پیشنهاد می‌دهد؛ هیچ مقداری خودکار بازنویسی نمی‌شود.</span></div>{duplicates.map((item) => <article key={item.id}><span className="record-avatar">{item.displayName[0]}</span><div><strong>{item.displayName}</strong><small>{duplicateReasons(customer, item)}</small></div>{can(state.activeUser, 'crm.customers.merge') && <button className="button button--secondary" onClick={() => setMergeTarget(item)}><Merge size={17} /> بررسی ادغام</button>}</article>)}{!duplicates.length && <Empty text="پرونده مشابهی با تلفن یا شناسه یکسان پیدا نشد." />}</div>}
  </div>{mergeTarget && <div className="inline-confirm"><strong>ادغام «{mergeTarget.displayName}» در این پرونده؟</strong><p>تماس‌ها، نشانی‌ها، یادداشت‌ها، منشأ و تاریخچه حفظ می‌شوند. پرونده تکراری فقط غیرفعال و ارجاع‌داده می‌شود.</p><div><button className="button button--secondary" onClick={() => setMergeTarget(null)}>انصراف</button><button className="button button--danger" onClick={() => onMerge(mergeTarget.id)}>تأیید ادغام</button></div></div>}</Modal>;
}

function CustomerDialog({customer, state, onClose, onSubmit}: {customer?: CustomerRecord; state: FoundationState; onClose: () => void; onSubmit: (input: CustomerInput) => void}) {
  const [tab, setTab] = useState<'identity' | 'contact' | 'relationships' | 'notes'>('identity'); const [form, setForm] = useState<CustomerInput>(() => customer ? stripCustomer(customer) : emptyCustomer());
  const [errors,setErrors]=useState<string[]>([]);
  const set = <K extends keyof CustomerInput>(key: K, value: CustomerInput[K]) => setForm((current) => ({...current, [key]: value}));
  const updatePhone = (id: string, patch: Partial<CustomerPhone>) => set('phones', form.phones.map((item) => item.id === id ? {...item, ...patch} : item)); const updateAddress = (id: string, patch: Partial<CustomerAddress>) => set('addresses', form.addresses.map((item) => item.id === id ? {...item, ...patch} : item)); const updateRelation = (id: string, patch: Partial<CustomerRelationship>) => set('relationships', form.relationships.map((item) => item.id === id ? {...item, ...patch} : item));
  return <Modal onClose={onClose} wide><Heading eyebrow="پرونده مشتری" title={customer ? `ویرایش ${customer.displayName}` : 'ایجاد مشتری جدید'} text="هویت مشتری از پرسنل و حساب کاربری مستقل است." onClose={onClose} /><div className="record-tabs">{[{id:'identity',label:'هویت و مالک'},{id:'contact',label:'تماس و نشانی'},{id:'relationships',label:'ارتباط‌ها'},{id:'notes',label:'یادداشت'}].map((item) => <button key={item.id} className={tab === item.id ? 'active' : ''} onClick={() => setTab(item.id as typeof tab)}>{item.label}</button>)}</div><div className="record-tab-body">
    {tab === 'identity' && <div className="org-form-grid"><Field label="نوع مشتری" required><select aria-required="true" value={form.type} onChange={(e) => set('type', e.target.value as CustomerInput['type'])}><option value="individual">شخص حقیقی</option><option value="legal">شخص حقوقی</option></select></Field><Field label="وضعیت" required><select aria-required="true" value={form.status} disabled={Boolean(customer) && !can(state.activeUser, 'crm.customers.status.manage')} onChange={(e) => set('status', e.target.value as CustomerStatus)}><option value="active">فعال</option><option value="prospect">بالقوه</option><option value="inactive">غیرفعال</option></select></Field>{form.type === 'individual' ? <><Field label="نام" required><input aria-required="true" value={form.firstName ?? ''} onChange={(e) => set('firstName', e.target.value)} /></Field><Field label="نام خانوادگی" required><input aria-required="true" value={form.lastName ?? ''} onChange={(e) => set('lastName', e.target.value)} /></Field><Field label="کد ملی"><input value={form.nationalId ?? ''} onChange={(e) => set('nationalId', e.target.value)} /></Field></> : <><Field label="نام حقوقی" full required><input aria-required="true" value={form.legalName ?? ''} onChange={(e) => set('legalName', e.target.value)} /></Field><Field label="شناسه ملی"><input value={form.businessId ?? ''} onChange={(e) => set('businessId', e.target.value)} /></Field><Field label="کد اقتصادی"><input value={form.economicCode ?? ''} onChange={(e) => set('economicCode', e.target.value)} /></Field></>}<Field label="مالک پرونده"><select value={form.ownerPersonnelId ?? ''} onChange={(e) => set('ownerPersonnelId', e.target.value || undefined)}><option value="">تعیین نشده</option>{state.personnel.filter((item) => item.employmentStatus === 'active').map((item) => <option key={item.id} value={item.id}>{item.firstName} {item.lastName}</option>)}</select></Field><Field label="منبع آشنایی" required><input aria-required="true" value={form.source} onChange={(e) => set('source', e.target.value)} placeholder="معرفی، وب‌سایت، رویداد..." /></Field><Field label="منشأ داده" full required><input aria-required="true" value={form.provenance} onChange={(e) => set('provenance', e.target.value)} placeholder="ثبت دستی توسط پذیرش" /></Field></div>}
    {tab === 'contact' && <div className="repeatable-section"><div className="repeatable-heading"><div><strong>شماره‌های تماس</strong><small>شماره اصلی در فهرست نمایش داده می‌شود.</small></div><button className="button button--secondary" onClick={() => set('phones', [...form.phones, {id: localId('phone'), label: 'تماس', number: '', primary: !form.phones.length}])}><Plus size={16} /> افزودن</button></div>{form.phones.map((phone) => <div className="repeatable-row" key={phone.id}><input aria-label="عنوان شماره" value={phone.label} onChange={(e) => updatePhone(phone.id, {label: e.target.value})} /><input aria-label="شماره تماس" value={phone.number} onChange={(e) => updatePhone(phone.id, {number: digitsOnly(e.target.value, 11)})} inputMode="tel" dir="ltr" maxLength={11} placeholder="09125026707"/><label className="tiny-check"><input type="radio" name="primary-phone" checked={phone.primary} onChange={() => set('phones', form.phones.map((item) => ({...item, primary: item.id === phone.id})))} /> اصلی</label><Icon label="حذف شماره" tone="danger" onClick={() => set('phones', form.phones.filter((item) => item.id !== phone.id))}><X size={16} /></Icon></div>)}<Field label="ایمیل"><input type="email" value={form.email ?? ''} onChange={(e) => set('email', e.target.value)} /></Field><div className="repeatable-heading"><div><strong>نشانی‌ها</strong><small>برای هر محل یک رکورد مستقل نگه دارید.</small></div><button className="button button--secondary" onClick={() => set('addresses', [...form.addresses, {id: localId('address'), label: 'نشانی', address: '', primary: !form.addresses.length}])}><Plus size={16} /> افزودن</button></div>{form.addresses.map((address) => <div className="address-editor" key={address.id}><input aria-label="عنوان نشانی" value={address.label} onChange={(e) => updateAddress(address.id, {label: e.target.value})} /><input aria-label="استان" value={address.province ?? ''} onChange={(e) => updateAddress(address.id, {province: e.target.value})} placeholder="استان" /><input aria-label="شهر" value={address.city ?? ''} onChange={(e) => updateAddress(address.id, {city: e.target.value})} placeholder="شهر" /><input aria-label="کد پستی" value={address.postalCode ?? ''} onChange={(e) => updateAddress(address.id, {postalCode: normalizePostalCode(e.target.value)})} placeholder="کد پستی ۱۰ رقمی" inputMode="numeric" dir="ltr" maxLength={10}/><input aria-label="نشانی" value={address.address} onChange={(e) => updateAddress(address.id, {address: e.target.value})} placeholder="نشانی کامل" /><label className="tiny-check"><input type="radio" name="primary-address" checked={address.primary} onChange={() => set('addresses', form.addresses.map((item) => ({...item, primary: item.id === address.id})))} /> اصلی</label><Icon label="حذف نشانی" tone="danger" onClick={() => set('addresses', form.addresses.filter((item) => item.id !== address.id))}><X size={16} /></Icon></div>)}</div>}
    {tab === 'relationships' && <div className="repeatable-section"><div className="repeatable-heading"><div><strong>ارتباط‌های مشتری</strong><small>افراد یا مشتریان مرتبط را بدون ساخت داده ساختگی ثبت کنید.</small></div><button className="button button--secondary" onClick={() => set('relationships', [...form.relationships, {id: localId('relation'), title: 'رابط', personName: ''}])}><Plus size={16} /> افزودن</button></div>{form.relationships.map((relation) => <div className="repeatable-row relationship-row" key={relation.id}><input aria-label="نوع ارتباط" value={relation.title} onChange={(e) => updateRelation(relation.id, {title: e.target.value})} /><input aria-label="نام فرد مرتبط" value={relation.personName ?? ''} onChange={(e) => updateRelation(relation.id, {personName: e.target.value})} /><input aria-label="توضیح ارتباط" value={relation.description ?? ''} onChange={(e) => updateRelation(relation.id, {description: e.target.value})} /><Icon label="حذف ارتباط" tone="danger" onClick={() => set('relationships', form.relationships.filter((item) => item.id !== relation.id))}><X size={16} /></Icon></div>)}</div>}
    {tab === 'notes' && <Field label="یادداشت داخلی" full><textarea className="large-textarea" value={form.notes} onChange={(e) => set('notes', e.target.value)} placeholder="نکته‌های مرتبط با رابطه مشتری را اینجا ثبت کنید." /></Field>}
  </div><FormValidationSummary errors={errors}/><div className="dialog-actions"><button className="button button--secondary" onClick={onClose}>انصراف</button><button className="button button--primary" onClick={() => {const next=validateRequired([...(form.type==='individual'?[{label:'نام',value:form.firstName},{label:'نام خانوادگی',value:form.lastName}]:[{label:'نام حقوقی',value:form.legalName}]),{label:'منبع آشنایی',value:form.source},{label:'منشأ داده',value:form.provenance}]);setErrors(next);if(next.length){setTab('identity');return;}onSubmit(form);}}>{customer ? 'ذخیره تغییرات' : 'ایجاد مشتری'}</button></div></Modal>;
}

function ImportDialog({state, onClose, onImport}: {state: FoundationState; onClose: () => void; onImport: (rows: CustomerImportRow[], name: string) => void}) { const [rows, setRows] = useState<CustomerImportRow[]>([]); const [fileName, setFileName] = useState(''); const [error, setError] = useState(''); const pick = (event: ChangeEvent<HTMLInputElement>) => {const file = event.target.files?.[0]; if (!file) return; setFileName(file.name); file.text().then((text) => {try {setRows(parseCsv(text)); setError('');} catch (cause) {setError(cause instanceof Error ? cause.message : 'فایل قابل خواندن نیست.');}});}; const preview = rows.slice(0, 8); return <Modal onClose={onClose} wide><Heading eyebrow="ورود گروهی مشتری" title="پیش‌نمایش CSV" text="پیش از ورود، اعتبار و مشابهت امن بررسی می‌شود؛ رکورد تکراری خودکار بازنویسی نخواهد شد." onClose={onClose} /><label className="csv-drop"><FileUp size={28} /><strong><RequiredLabel>{fileName || 'فایل CSV را انتخاب کنید'}</RequiredLabel></strong><span>ستون‌های پیشنهادی: name, type, nationalId, businessId, phone, email, source</span><input type="file" aria-required="true" accept=".csv,text/csv" onChange={pick} /></label>{error && <div className="inline-error" role="alert">{error}</div>}{rows.length > 0 && <><div className="import-summary"><span><b>{rows.length.toLocaleString('en-US')}</b> ردیف</span><span><b>{rows.filter((row) => Boolean(findDuplicateCustomers(state.customers, rowAsInput(row)).length)).length.toLocaleString('en-US')}</b> مشابه احتمالی</span></div><div className="import-preview"><div><b>نام</b><b>نوع</b><b>تماس</b><b>نتیجه پیش‌نمایش</b></div>{preview.map((row, index) => {const duplicate = findDuplicateCustomers(state.customers, rowAsInput(row)).length > 0; return <div key={`${row.name}-${index}`}><span>{row.name || '—'}</span><span>{row.type || 'حقیقی'}</span><span>{row.phone || '—'}</span><span className={duplicate ? 'preview-duplicate' : 'preview-valid'}>{duplicate ? 'نیازمند بررسی / رد ورود خودکار' : row.name ? 'آماده ورود' : 'نامعتبر'}</span></div>})}</div></>}<div className="dialog-actions"><button className="button button--secondary" onClick={onClose}>انصراف</button><button className="button button--primary" onClick={() => {if(!rows.length){setError('فیلد «فایل CSV» الزامی است؛ لطفاً فایل معتبر را انتخاب و بررسی کنید.');return;}onImport(rows,fileName);}}>تأیید و ورود رکوردهای معتبر</button></div></Modal>; }

function parseCsv(text: string): CustomerImportRow[] { const lines = text.replace(/^\uFEFF/, '').split(/\r?\n/).filter((line) => line.trim()); if (lines.length < 2) throw new Error('فایل باید سطر عنوان و حداقل یک مشتری داشته باشد.'); const headers = splitCsvLine(lines[0]).map((item) => item.trim()); const index = (name: string) => headers.findIndex((item) => item.toLowerCase() === name.toLowerCase()); if (index('name') < 0) throw new Error('ستون name در فایل وجود ندارد.'); return lines.slice(1).map((line) => {const values = splitCsvLine(line); const read = (name: string) => values[index(name)]?.trim() || undefined; return {name: read('name') ?? '', type: read('type'), nationalId: read('nationalId'), businessId: read('businessId'), phone: read('phone'), email: read('email'), source: read('source')};}); }
function splitCsvLine(line: string) { const values: string[] = []; let current = ''; let quoted = false; for (let i = 0; i < line.length; i += 1) {const char = line[i]; if (char === '"' && line[i + 1] === '"') {current += '"'; i += 1;} else if (char === '"') quoted = !quoted; else if (char === ',' && !quoted) {values.push(current); current = '';} else current += char;} values.push(current); return values; }
function rowAsInput(row: CustomerImportRow): CustomerInput { const type = row.type === 'legal' || row.type === 'حقوقی' ? 'legal' : 'individual'; const names = row.name.trim().split(/\s+/); return {type, firstName: type === 'individual' ? names.slice(0,-1).join(' ') || names[0] : undefined, lastName: type === 'individual' ? names.at(-1) : undefined, legalName: type === 'legal' ? row.name : undefined, nationalId: row.nationalId, businessId: row.businessId, status: 'active', phones: row.phone ? [{id:'preview',label:'اصلی',number:row.phone,primary:true}] : [], email: row.email, addresses: [], source: row.source || 'CSV', provenance: 'پیش‌نمایش', notes:'', relationships:[]}; }
function emptyCustomer(): CustomerInput { return {type: 'individual', firstName: '', lastName: '', status: 'prospect', phones: [{id: localId('phone'), label: 'همراه', number: '', primary: true}], addresses: [], source: '', provenance: 'ثبت دستی در تپرا', notes: '', relationships: []}; }
function stripCustomer(record: CustomerRecord): CustomerInput { const {id:_id, displayName:_displayName, timeline:_timeline, mergedIntoCustomerId:_merged, createdAt:_created, updatedAt:_updated, ...input} = record; return structuredClone(input); }
function localId(prefix: string) { return `${prefix}-${crypto.randomUUID()}`; }
function statusLabel(status: CustomerStatus) { return status === 'active' ? 'فعال' : status === 'inactive' ? 'غیرفعال' : 'بالقوه'; }
function duplicateReasons(a: CustomerRecord, b: CustomerRecord) { const reasons: string[] = []; if (a.nationalId && a.nationalId === b.nationalId) reasons.push('کد ملی یکسان'); if (a.businessId && a.businessId === b.businessId) reasons.push('شناسه ملی یکسان'); if (a.phones.some((phone) => b.phones.some((other) => phone.number === other.number))) reasons.push('شماره تماس یکسان'); return reasons.join('، ') || 'شباهت اطلاعات تماس'; }
function Metric({value, label, warn}: {value: number; label: string; warn?: boolean}) { return <article className={warn ? 'metric-warn' : ''}><span>{warn ? <CircleAlert size={19} /> : <UsersRound size={19} />}</span><div><strong>{value.toLocaleString('en-US')}</strong><b>{label}</b><small>پرونده محلی ساختاریافته</small></div></article>; }
function Summary({icon, title, value}: {icon: ReactNode; title: string; value: string}) { return <article><span>{icon}</span><div><small>{title}</small><strong>{value}</strong></div></article>; }
function Detail({label, value}: {label: string; value?: string}) { return <span><small>{label}</small><strong>{value || 'ثبت نشده'}</strong></span>; }
function Empty({text}: {text: string}) { return <div className="table-empty"><CircleAlert size={22} /><span>{text}</span></div>; }
function Field({label, full = false, required = false, children}: {label: string; full?: boolean; required?: boolean; children: ReactNode}) { return <label className={`field-label ${full ? 'field-label--full' : ''}`}>{required ? <RequiredLabel>{label}</RequiredLabel> : <OptionalLabel>{label}</OptionalLabel>}{children}</label>; }
function Icon({label, tone = 'neutral', onClick, children}: {label: string; tone?: string; onClick: () => void; children: ReactNode}) { return <button type="button" className={`icon-action icon-action--${tone}`} aria-label={label} data-tooltip={label} onClick={onClick}>{children}</button>; }
function Modal({children, onClose, wide = false}: {children: ReactNode; onClose: () => void; wide?: boolean}) { return <div className="modal-layer" role="dialog" aria-modal="true"><button className="modal-scrim" aria-label="بستن" onClick={onClose} /><section className={`modal-card ${wide ? 'modal-card--wide modal-card--record' : ''}`}>{children}</section></div>; }
function Heading({eyebrow, title, text, onClose, action}: {eyebrow: string; title: string; text: string; onClose: () => void; action?: ReactNode}) { return <div className="modal-heading"><div><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>{action}<button className="icon-button" aria-label="بستن پنجره" onClick={onClose}><X size={20} /></button></div>; }
function ConfirmDialog({title, text, confirm, danger, onClose, onConfirm}: {title: string; text: string; confirm: string; danger?: boolean; onClose: () => void; onConfirm: () => void}) { return <Modal onClose={onClose}><div className="danger-symbol"><Power size={27} /></div><div className="centered-modal"><h2>{title}</h2><p>{text}</p><div className="modal-actions modal-actions--center"><button className="button button--secondary" onClick={onClose}>انصراف</button><button className={`button ${danger ? 'button--danger' : 'button--primary'}`} onClick={onConfirm}>{confirm}</button></div></div></Modal>; }
