import {useMemo,useState,type ChangeEvent} from 'react';
import {Archive,CheckCheck,Download,FileText,Inbox,Mail,Paperclip,Send,ShieldCheck,X} from 'lucide-react';
import type {FoundationState,OperationalRecord} from './model';
import type {LocalFoundationService} from './service';
import {can} from './authorization';
import {permissionFor} from './erpCatalog';
import {FormValidationSummary,RequiredLabel} from './FormValidation';
import {RecordDialog} from './RecordDialog';
import {letterAttachment,letterBody,letterDirection,letterDirectionLabel,letterExternalParty,letterRecipientUserIds,letterStatusLabel,MAX_LETTER_FILE_SIZE,type LetterAttachmentInput,type LetterDirection,type LetterInput} from './letters';

interface Props{state:FoundationState;service:LocalFoundationService;execute:(label:string,work:()=>Promise<FoundationState>,success:string)=>Promise<boolean>}
type Box='inbox'|'outbox'|'drafts'|'review';
const dateTime=new Intl.DateTimeFormat('fa-IR',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});

export function LettersPage({state,service,execute}:Props){
  const [box,setBox]=useState<Box>('inbox');const [compose,setCompose]=useState(false);const [selected,setSelected]=useState<OperationalRecord>();
  const letters=useMemo(()=>state.operationalRecords.filter((record)=>record.moduleId==='letter'),[state.operationalRecords]);
  const mine=(record:OperationalRecord)=>record.createdByUserId===state.activeUser.id;const recipient=(record:OperationalRecord)=>letterRecipientUserIds(record).includes(state.activeUser.id)&&record.status==='sent';
  const mayReview=can(state.activeUser,permissionFor('letter','approve'));
  const outgoing=(record:OperationalRecord)=>mine(record)&&letterDirection(record)!=='incoming';
  const shown=letters.filter((record)=>box==='inbox'?recipient(record):box==='outbox'?outgoing(record)&&record.status!=='draft':box==='drafts'?outgoing(record)&&record.status==='draft':mayReview&&['in_review','approved_for_send'].includes(record.status));
  const counts:{box:Box;label:string;icon:typeof Inbox;count:number}[]=[
    {box:'inbox',label:'دریافتی',icon:Inbox,count:letters.filter(recipient).length},
    {box:'outbox',label:'ارسالی و در جریان',icon:Send,count:letters.filter((record)=>outgoing(record)&&record.status!=='draft').length},
    {box:'drafts',label:'پیش‌نویس‌ها',icon:FileText,count:letters.filter((record)=>outgoing(record)&&record.status==='draft').length},
    ...(mayReview?[{box:'review' as const,label:'صف بازبینی',icon:ShieldCheck,count:letters.filter((record)=>['in_review','approved_for_send'].includes(record.status)).length}]:[]),
  ];
  return <section className="letters-page"><header className="letters-hero"><div><span className="eyebrow">دبیرخانه دیجیتال</span><h2>نامه‌نگاری سازمانی</h2><p>نامه‌های داخلی، وارده و صادره را از پیش‌نویس تا مجوز ارسال در یک کارتابل نگه دارید.</p></div><button className="button button--primary" onClick={()=>setCompose(true)}><Mail size={18}/> نامه جدید</button></header>
    <nav className="letter-boxes" aria-label="کارتابل نامه‌ها">{counts.map((item)=>{const Icon=item.icon;return <button key={item.box} className={box===item.box?'letter-box letter-box--active':'letter-box'} aria-current={box===item.box?'page':undefined} onClick={()=>setBox(item.box)}><Icon size={19}/><span>{item.label}</span><b>{item.count.toLocaleString('fa-IR')}</b></button>;})}</nav>
    <div className="letter-list">{shown.map((record)=><button key={record.id} className="letter-row" onClick={()=>setSelected(record)}><span className="letter-direction"><Mail size={18}/>{letterDirectionLabel(letterDirection(record))}</span><span><strong>{record.title}</strong><small>{record.trackingCode} · {letterExternalParty(record)||recipientNames(record,state)}</small></span><span className={`state-badge state-badge--${record.status==='sent'?'done':record.status==='draft'?'neutral':'progress'}`}>{letterStatusLabel(record.status)}</span><time>{dateTime.format(new Date(record.updatedAt))}</time></button>)}{!shown.length&&<div className="letter-empty"><Archive size={42}/><h3>این کارتابل خالی است</h3><p>{box==='drafts'?'برای شروع یک نامه جدید بسازید.':'نامه‌ای با این وضعیت برای شما وجود ندارد.'}</p></div>}</div>
    {compose&&<ComposeLetterDialog state={state} mayRegisterIncoming={can(state.activeUser,permissionFor('letter','create'))} onClose={()=>setCompose(false)} onSave={async(input)=>{const ok=await execute('letter-create',()=>service.createLetter(input),'نامه ثبت شد.');if(ok)setCompose(false);}}/>}
    {selected&&<LetterDetailDialog record={selected} state={state} onClose={()=>setSelected(undefined)} onAction={async(action)=>{const ok=await execute(`letter-${action}`,()=>service.transitionLetter(selected.id,selected.version,action),action==='approve'?'مجوز ارسال نامه ثبت شد.':action==='send'?'نامه ارسال شد.':'نامه برای بازبینی فرستاده شد.');if(ok)setSelected(undefined);}}/>}
  </section>;
}

function ComposeLetterDialog({state,mayRegisterIncoming,onClose,onSave}:{state:FoundationState;mayRegisterIncoming:boolean;onClose:()=>void;onSave:(input:LetterInput)=>Promise<void>}){
  const [direction,setDirection]=useState<LetterDirection>('internal');const [subject,setSubject]=useState('');const [body,setBody]=useState('');const [externalParty,setExternalParty]=useState('');const [recipients,setRecipients]=useState<string[]>([]);const [attachment,setAttachment]=useState<LetterAttachmentInput>();const [errors,setErrors]=useState<string[]>([]);const [saving,setSaving]=useState(false);
  const candidates=state.users.filter((user)=>user.status==='active'&&user.companyId===state.activeUser.companyId&&user.id!==state.activeUser.id);
  const readFile=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;if(file.size>MAX_LETTER_FILE_SIZE){setErrors(['حجم پیوست نامه بیشتر از ۱۰ مگابایت است.']);return;}const reader=new FileReader();reader.onerror=()=>setErrors(['خواندن پیوست ممکن نشد؛ دوباره انتخاب کنید.']);reader.onload=()=>{if(typeof reader.result==='string'){setAttachment({fileName:file.name,mimeType:file.type,size:file.size,dataUrl:reader.result});setErrors([]);}};reader.readAsDataURL(file);};
  const submit=async()=>{if(saving)return;const next:string[]=[];if(subject.trim().length<3)next.push('موضوع نامه را وارد کنید.');if(body.trim().length<5)next.push('متن نامه را کامل کنید.');if(direction!=='outgoing'&&!recipients.length)next.push('حداقل یک گیرنده داخلی انتخاب کنید.');if(direction!=='internal'&&externalParty.trim().length<2)next.push(direction==='incoming'?'نام فرستنده بیرونی را وارد کنید.':'نام گیرنده بیرونی را وارد کنید.');setErrors(next);if(next.length)return;setSaving(true);try{await onSave({direction,subject,body,externalParty,recipientUserIds:recipients,attachment});}finally{setSaving(false);}};
  const safeClose=()=>{if(!saving)onClose();};
  const directions=[{id:'internal' as const,label:'داخلی'},{id:'outgoing' as const,label:'صادره'},...(mayRegisterIncoming?[{id:'incoming' as const,label:'وارده'}]:[])];
  return <RecordDialog ariaLabel="ثبت نامه جدید" className="letter-compose-dialog" onClose={safeClose}><header><div><span className="eyebrow">نامه جدید</span><h2>ثبت نامه سازمانی</h2></div><button className="icon-button" disabled={saving} onClick={safeClose} aria-label="بستن"><X size={20}/></button></header><fieldset className="drawer-body letter-compose-fields" disabled={saving}><FormValidationSummary errors={errors}/><div className="letter-direction-picker" role="radiogroup" aria-label="نوع نامه">{directions.map((item)=><button type="button" role="radio" aria-checked={direction===item.id} className={direction===item.id?'active':''} key={item.id} onClick={()=>{setDirection(item.id);setRecipients([]);}}>{item.label}</button>)}</div><label className="field"><RequiredLabel>موضوع</RequiredLabel><input value={subject} onChange={(event)=>setSubject(event.target.value)} autoFocus/></label>{direction!=='internal'&&<label className="field"><RequiredLabel>{direction==='incoming'?'فرستنده بیرونی':'گیرنده بیرونی'}</RequiredLabel><input value={externalParty} onChange={(event)=>setExternalParty(event.target.value)} placeholder="نام شخص یا سازمان"/></label>}<label className="field"><RequiredLabel>متن نامه</RequiredLabel><textarea rows={8} maxLength={12000} value={body} onChange={(event)=>setBody(event.target.value)}/></label>{direction!=='outgoing'&&<fieldset className="letter-recipient-picker"><legend>گیرندگان داخلی</legend>{candidates.map((user)=><label key={user.id}><input type="checkbox" checked={recipients.includes(user.id)} onChange={()=>setRecipients((current)=>current.includes(user.id)?current.filter((id)=>id!==user.id):[...current,user.id])}/><span><strong>{user.name}</strong><small><bdi dir="ltr">@{user.username}</bdi> · {state.units.find((unit)=>unit.id===user.unitId)?.name??'بدون واحد'}</small></span></label>)}</fieldset>}<label className="letter-attachment"><Paperclip size={20}/><span><strong>{attachment?.fileName??'افزودن پیوست'}</strong><small>{attachment?formatBytes(attachment.size):'PDF، تصویر، متن یا Word تا ۱۰ مگابایت'}</small></span><input hidden type="file" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,.docx" onChange={readFile}/></label></fieldset><footer><button className="button button--ghost" disabled={saving} onClick={safeClose}>انصراف</button><button className="button button--primary" disabled={saving} onClick={()=>void submit()}>{saving?'در حال ثبت…':'ثبت نامه'}</button></footer></RecordDialog>;
}

function LetterDetailDialog({record,state,onClose,onAction}:{record:OperationalRecord;state:FoundationState;onClose:()=>void;onAction:(action:'submit_review'|'approve'|'send')=>Promise<void>}){
  const attachment=letterAttachment(record);const [busy,setBusy]=useState(false);const run=async(action:'submit_review'|'approve'|'send')=>{if(busy)return;setBusy(true);try{await onAction(action);}finally{setBusy(false);}};const mine=record.createdByUserId===state.activeUser.id;const mayApprove=can(state.activeUser,permissionFor('letter','approve'))&&record.createdByUserId!==state.activeUser.id;
  return <RecordDialog ariaLabel={`نامه ${record.trackingCode}`} className="letter-detail-dialog" onClose={()=>{if(!busy)onClose();}}><header><div><span className="eyebrow">{record.trackingCode}</span><h2>{record.title}</h2></div><button className="icon-button" disabled={busy} onClick={onClose} aria-label="بستن"><X size={20}/></button></header><div className="drawer-body letter-detail"><div className="letter-facts"><span><small>نوع</small><strong>{letterDirectionLabel(letterDirection(record))}</strong></span><span><small>وضعیت</small><strong>{letterStatusLabel(record.status)}</strong></span><span><small>ثبت‌کننده</small><strong>{state.users.find((user)=>user.id===record.createdByUserId)?.name??'کاربر سازمانی'}</strong></span><span><small>مخاطب</small><strong>{letterExternalParty(record)||recipientNames(record,state)||'ثبت نشده'}</strong></span></div><article className="letter-body"><FileText size={24}/><p>{letterBody(record)}</p></article>{attachment&&<a className="letter-download" href={attachment.dataUrl} download={attachment.fileName}><Download size={19}/><span><strong>{attachment.fileName}</strong><small>{formatBytes(attachment.size)}</small></span></a>}<section className="letter-history"><h3>گردش نامه</h3>{state.operationalHistory.filter((item)=>item.recordId===record.id).map((item)=><div key={item.id}><CheckCheck size={16}/><span><strong>{item.actorName}</strong><small>{item.fromState?`${letterStatusLabel(item.fromState)} ← ${letterStatusLabel(item.toState??'')}`:'نامه ثبت شد'} · {dateTime.format(new Date(item.occurredAt))}</small></span></div>)}</section></div><footer><button className="button button--ghost" disabled={busy} onClick={onClose}>بستن</button>{mine&&record.status==='draft'&&<button className="button button--primary" disabled={busy} onClick={()=>void run('submit_review')}><Send size={17}/> ارسال برای بازبینی</button>}{mayApprove&&record.status==='in_review'&&<button className="button button--primary" disabled={busy} onClick={()=>void run('approve')}><ShieldCheck size={17}/> صدور مجوز ارسال</button>}{mine&&record.status==='approved_for_send'&&<button className="button button--primary" disabled={busy} onClick={()=>void run('send')}><Send size={17}/> ارسال نهایی</button>}</footer></RecordDialog>;
}
function recipientNames(record:OperationalRecord,state:FoundationState){return letterRecipientUserIds(record).map((id)=>state.users.find((user)=>user.id===id)?.name).filter(Boolean).join('، ');}
function formatBytes(size:number){return size<1024*1024?`${Math.max(1,Math.round(size/1024)).toLocaleString('fa-IR')} کیلوبایت`:`${(size/1024/1024).toLocaleString('fa-IR',{maximumFractionDigits:1})} مگابایت`;}
