import {describe, expect, it} from 'vitest';
import type {FoundationSession, FoundationStoreName, LocalUser, OperationalRecord, OperationalRecordHistory, PersonnelRecord, RecruitmentCandidateFile, SalesStructure, SecurityRole, SnapshotManifest} from './model';
import {FOUNDATION_STORES} from './model';
import {createSeedData} from './seed';
import {LocalFoundationService} from './service';
import type {StorageAdapter, StorageTransaction} from './storage';
import {managedSalesBranchIdsForPersonnel, resolveWorkforceRequestScope} from './salesManagementScope';
import {matchesRecruitmentBankFilter, matchesRecruitmentCandidateQuery, recruitmentReachedInterview} from './recruitmentCandidateBank';

class MemoryStorage implements StorageAdapter {
  private stores = new Map<FoundationStoreName, Map<IDBValidKey, unknown>>(FOUNDATION_STORES.map((store)=>[store,new Map()]));
  private beforeNextReadwrite?:()=>void;
  revokeRoleBeforeNextReadwrite(userId:string,roleId:string){this.beforeNextReadwrite=()=>{const user=this.stores.get('users')?.get(userId) as LocalUser;this.stores.get('users')!.set(userId,{...user,roleIds:user.roleIds.filter((id)=>id!==roleId),roleId:user.roleId===roleId?'role-employee':user.roleId,permissionDenials:[...(user.permissionDenials??[]),'hr.recruitment_case.transition']});};}
  deactivateRoleBeforeNextReadwrite(roleId:string){this.beforeNextReadwrite=()=>{const role=this.stores.get('security_roles')?.get(roleId) as SecurityRole;this.stores.get('security_roles')!.set(roleId,{...role,status:'inactive',version:(role.version??1)+1});};}
  switchSessionBeforeNextReadwrite(activeUserId:string){this.beforeNextReadwrite=()=>{const session=this.stores.get('sessions')?.get('active-session') as FoundationSession;this.stores.get('sessions')!.set('active-session',{...session,activeUserId,actingAdminUserId:undefined,version:session.version+1,switchedAt:new Date().toISOString()});};}
  changeUnitCompanyBeforeNextReadwrite(unitId:string,companyId:string){this.beforeNextReadwrite=()=>{const unit=this.stores.get('organizational_units')?.get(unitId) as {id:string;companyId?:string};this.stores.get('organizational_units')!.set(unitId,{...unit,companyId});};}
  async transaction<T>(stores: FoundationStoreName[], mode: IDBTransactionMode, work: (transaction: StorageTransaction)=>Promise<T>): Promise<T> {if(mode==='readwrite'&&this.beforeNextReadwrite){const mutate=this.beforeNextReadwrite;this.beforeNextReadwrite=undefined;mutate();}const tx:StorageTransaction={get:async<V>(store,id)=>this.stores.get(store)?.get(id) as V|undefined,getAll:async<V>(store)=>[...(this.stores.get(store)?.values()??[])] as V[],put:async(store,value)=>{this.stores.get(store)!.set((value as {id:IDBValidKey}).id,structuredClone(value));},delete:async(store,id)=>{this.stores.get(store)!.delete(id);},clear:async(store)=>{this.stores.get(store)!.clear();}};return work(tx);}
  get<T>(store:FoundationStoreName,id:IDBValidKey){return this.transaction([store],'readonly',(tx)=>tx.get<T>(store,id));}
  getAll<T>(store:FoundationStoreName){return this.transaction([store],'readonly',(tx)=>tx.getAll<T>(store));}
  put<T>(store:FoundationStoreName,value:T){return this.transaction([store],'readwrite',(tx)=>tx.put(store,value));}
  delete(store:FoundationStoreName,id:IDBValidKey){return this.transaction([store],'readwrite',(tx)=>tx.delete(store,id));}
  async replaceAll(stores:Record<FoundationStoreName,unknown[]>){for(const store of FOUNDATION_STORES){this.stores.get(store)!.clear();for(const value of stores[store])this.stores.get(store)!.set((value as {id:IDBValidKey}).id,structuredClone(value));}}
  async exportSnapshot():Promise<SnapshotManifest>{throw new Error('not used');} async importSnapshot():Promise<void>{throw new Error('not used');}
}

async function setup(){const storage=new MemoryStorage();await storage.replaceAll(createSeedData());const ready=await storage.get<OperationalRecord>('recruitment_cases','recruitment-case-004');if(ready)await storage.put('recruitment_cases',{...ready,payload:{...ready.payload,candidateNationalId:'1234567891'}});const session=(await storage.get<FoundationSession>('sessions','active-session'))!;return{storage,session,service:new LocalFoundationService(storage)};}
const login=(storage:MemoryStorage,session:FoundationSession,activeUserId:string)=>storage.put('sessions',{...session,activeUserId,actingAdminUserId:undefined});

describe('recruitment lifecycle',()=>{
  it('blocks the generic recruitment creator and non-assigned stage actors',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-seller');await expect(service.createOperationalRecord('recruitment-case',{title:'دورزدن مسیر اختصاصی',unitId:'unit-sales',branchUnitId:'unit-branch-central'})).rejects.toThrow('مسیر اختصاصی');await expect(service.transitionOperationalRecord('recruitment-case','recruitment-case-001','recruitment-case.hr_review')).rejects.toThrow('مسئول ثبت‌شده');});

  it.each([
    ['role-workforce-requester','نقش فعال ثبت اعلام نیاز'],
    ['role-recruitment-operator','کارشناس جذب واجد شرایط'],
  ])('revalidates requester and exact operator role %s inside recruitment creation transaction',async(roleId,message)=>{const{storage,session,service}=await setup();const seller=(await storage.get<LocalUser>('users','persona-seller'))!;const workforceRole=(await storage.get<SecurityRole>('security_roles','role-workforce-requester'))!;const genericRole:SecurityRole={...workforceRole,id:'role-generic-recruitment-create',name:'مجوز عمومی ثبت جذب',status:'active',permissions:['hr.recruitment_case.create'],protected:false};await storage.put('security_roles',genericRole);await storage.put('users',{...seller,roleIds:[...seller.roleIds,genericRole.id]});await login(storage,session,'persona-seller');const beforeRecords=await storage.getAll('recruitment_cases'),beforeHistory=await storage.getAll('workflow_history'),beforeAudits=await storage.getAll('audit_events');storage.deactivateRoleBeforeNextReadwrite(roleId);await expect(service.createRecruitmentRequest({title:'درخواست رقابتی نقش فعال',description:'کنترل نقش داخل تراکنش',unitId:'unit-sales',branchUnitId:'unit-branch-central',positionTitle:'کارشناس فروش',requestedHeadcount:'1',employmentType:'تمام‌وقت',requestReason:'تکمیل ظرفیت مصوب واحد فروش'})).rejects.toThrow(message);expect(await storage.getAll('recruitment_cases')).toEqual(beforeRecords);expect(await storage.getAll('workflow_history')).toEqual(beforeHistory);expect(await storage.getAll('audit_events')).toEqual(beforeAudits);});

  it('revalidates the exact recruitment target company inside the create transaction',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-seller');const before=await storage.getAll('recruitment_cases');storage.changeUnitCompanyBeforeNextReadwrite('unit-sales','company-other');await expect(service.createRecruitmentRequest({title:'درخواست مقصد تغییرکرده',description:'کنترل مالکیت شرکت',unitId:'unit-sales',branchUnitId:'unit-branch-central',positionTitle:'کارشناس فروش',requestedHeadcount:'1',employmentType:'تمام‌وقت',requestReason:'تکمیل ظرفیت مصوب واحد فروش'})).rejects.toThrow(/شرکت|مالکیت/);expect(await storage.getAll('recruitment_cases')).toEqual(before);});

  it('seeds six complete deterministic dossiers including a historical rejected candidate',async()=>{const{service}=await setup();const state=await service.loadState();const records=state.operationalRecords.filter((item)=>item.moduleId==='recruitment-case');expect(records).toHaveLength(6);expect(new Set(records.map((item)=>item.status)).size).toBe(6);expect(records.every((item)=>item.payload.currentWaitingFor&&item.workflowVersion===1)).toBe(true);const rejected=records.find((item)=>item.id==='recruitment-case-006')!;const workforceRequest=records.find((item)=>item.id==='recruitment-case-001')!;expect(rejected.status).toBe('rejected');expect(recruitmentReachedInterview(rejected,state.operationalHistory)).toBe(true);expect(matchesRecruitmentBankFilter(rejected,state.operationalHistory,'reusable')).toBe(true);expect(matchesRecruitmentBankFilter(workforceRequest,state.operationalHistory,'all')).toBe(true);expect(matchesRecruitmentBankFilter(workforceRequest,state.operationalHistory,'interviewed')).toBe(false);expect(matchesRecruitmentCandidateQuery(rejected,'09121230061','پشتیبانی')).toBe(true);expect(matchesRecruitmentCandidateQuery(rejected,'0081234561','پشتیبانی')).toBe(true);});

  it('adds the talent-bank example during upgrade without rewriting prior recruitment dossiers',async()=>{const storage=new MemoryStorage();const legacy=createSeedData();const priorRecord=(legacy.recruitment_cases as OperationalRecord[]).find((item)=>item.id==='recruitment-case-002')!;const preservedRecord={...priorRecord,description:'یادداشت واقعی کارشناس باید در ارتقا حفظ شود.',payload:{...priorRecord.payload,recruiterPrivateMarker:'keep-this-value'},updatedAt:'2026-08-26T09:30:00.000Z'};legacy.recruitment_cases=(legacy.recruitment_cases as OperationalRecord[]).filter((item)=>item.id!=='recruitment-case-006').map((item)=>item.id===preservedRecord.id?preservedRecord:item);legacy.workflow_history=(legacy.workflow_history as OperationalRecordHistory[]).filter((item)=>item.recordId!=='recruitment-case-006');legacy.meta=legacy.meta.map((item)=>((item as {id:string}).id==='seedVersion'?{id:'seedVersion',value:'complete-local-erp-v1.35-collaboration-domain'}:item));await storage.replaceAll(legacy);const service=new LocalFoundationService(storage);let state=await service.initialize();expect(await storage.get('recruitment_cases',preservedRecord.id)).toEqual(preservedRecord);expect(state.operationalRecords.filter((item)=>item.id==='recruitment-case-006')).toHaveLength(1);expect(state.operationalHistory.some((item)=>item.recordId==='recruitment-case-006'&&item.toState==='rejected')).toBe(true);const first=await storage.getAll('recruitment_cases');state=await service.initialize();expect(await storage.getAll('recruitment_cases')).toEqual(first);expect(state.operationalRecords.filter((item)=>item.id==='recruitment-case-006')).toHaveLength(1);});

  it('upgrades the deterministic training case to one linked personnel identity exactly once',async()=>{const storage=new MemoryStorage();const legacy=createSeedData();legacy.personnel=legacy.personnel.filter((item)=>item.id!=='personnel-training-yasin');legacy.users=legacy.users.filter((item)=>item.id!=='persona-training-yasin');legacy.security_roles=legacy.security_roles.filter((item)=>item.id!=='role-training-personnel');legacy.recruitment_cases=(legacy.recruitment_cases as OperationalRecord[]).map((item)=>item.id!=='recruitment-case-005'?item:{...item,payload:{...item.payload,linkedPersonnelId:undefined,linkedUserId:undefined,candidateAccount:'فعال'}});legacy.meta=legacy.meta.map((item)=>((item as {id:string}).id==='seedVersion'?{id:'seedVersion',value:'complete-local-erp-v1.37-candidate-resume-files'}:item));await storage.replaceAll(legacy);const service=new LocalFoundationService(storage);let state=await service.initialize();const trainee=state.personnel.find((item)=>item.id==='personnel-training-yasin')!;const traineeUser=state.users.find((item)=>item.id==='persona-training-yasin')!;const recruitment=state.operationalRecords.find((item)=>item.id==='recruitment-case-005')!;expect(trainee).toMatchObject({employmentType:'آموزشی',linkedUserId:traineeUser.id,sourceRecruitmentRecordId:recruitment.id});expect(traineeUser).toMatchObject({personnelId:trainee.id,roleId:'role-training-personnel'});expect(recruitment.payload).toMatchObject({linkedPersonnelId:trainee.id,linkedUserId:traineeUser.id,candidateAccount:'فعال با دسترسی آموزشی محدود'});const firstPersonnel=await storage.getAll('personnel');const firstUsers=await storage.getAll('users');state=await service.initialize();expect(await storage.getAll('personnel')).toEqual(firstPersonnel);expect(await storage.getAll('users')).toEqual(firstUsers);expect(state.personnel.filter((item)=>item.personnelCode==='P-6105')).toHaveLength(1);});

  it('starts training atomically with a mandatory personnel file and an optional restricted account',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-callcenter-a');const state=await service.startRecruitmentTraining('recruitment-case-004',1,{firstName:'نازنین',lastName:'رضایی',startDate:'2026-08-27',unitId:'unit-sales',positionId:'position-seller',branchUnitId:'unit-branch-central',managerPersonnelId:'personnel-callcenter-a',createAccount:true,username:'n.rezaei.training',initialPassword:'Training@1405',note:'شروع دوره با نظارت سرپرست فروش'});const record=state.operationalRecords.find((item)=>item.id==='recruitment-case-004')!;const personnel=state.personnel.find((item)=>item.sourceRecruitmentRecordId===record.id)!;const rawPersonnel=(await storage.getAll<PersonnelRecord>('personnel')).find((item)=>item.sourceRecruitmentRecordId===record.id)!;const user=state.users.find((item)=>item.personnelId===personnel.id)!;expect(record).toMatchObject({status:'training',version:2});expect(record.payload).toMatchObject({linkedPersonnelId:personnel.id,linkedUserId:user.id,personnelCode:personnel.personnelCode,personnelStatus:'پرسنل آموزشی فعال',candidateAccount:'فعال با دسترسی آموزشی محدود'});expect(personnel).toMatchObject({employmentType:'آموزشی',employmentStatus:'active',linkedUserId:user.id,managerPersonnelId:'personnel-callcenter-a'});expect(rawPersonnel.advanceEligibilityStatus).toBe('ineligible');expect(user).toMatchObject({roleId:'role-training-personnel',roleIds:['role-training-personnel'],unitId:'unit-sales',positionId:'position-seller'});expect(state.operationalHistory.some((item)=>item.recordId===record.id&&item.toState==='training'&&item.snapshot.linkedPersonnelId===personnel.id)).toBe(true);expect((await storage.getAll<{action:string;metadata?:Record<string,unknown>}>('audit_events')).some((item)=>item.action==='hr.recruitment.training_started'&&item.metadata?.personnelId===personnel.id)).toBe(true);await expect(service.startRecruitmentTraining(record.id,1,{firstName:'نازنین',lastName:'رضایی',startDate:'2026-08-27',unitId:'unit-sales',positionId:'position-seller',createAccount:false})).rejects.toThrow('پنجره دیگری');expect((await storage.getAll<PersonnelRecord>('personnel')).filter((item)=>item.sourceRecruitmentRecordId===record.id)).toHaveLength(1);});

  it('can start training without a login account and blocks the generic transition bypass',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-callcenter-a');await expect(service.transitionOperationalRecord('recruitment-case','recruitment-case-004','recruitment-case.training')).rejects.toThrow('فرم تخصصی');const state=await service.startRecruitmentTraining('recruitment-case-004',1,{firstName:'نازنین',lastName:'رضایی',startDate:'2026-08-27',unitId:'unit-sales',positionId:'position-seller',branchUnitId:'unit-branch-central',managerPersonnelId:'personnel-callcenter-a',createAccount:false});const record=state.operationalRecords.find((item)=>item.id==='recruitment-case-004')!;const personnel=state.personnel.find((item)=>item.sourceRecruitmentRecordId===record.id)!;expect(personnel.linkedUserId).toBeUndefined();expect(record.payload).toMatchObject({linkedPersonnelId:personnel.id,linkedUserId:null,candidateAccount:'بدون حساب؛ فقط پرونده پرسنلی تشکیل شد'});expect(state.users.some((item)=>item.personnelId===personnel.id)).toBe(false);});

  it('fails closed when onboarding authority is revoked just before training starts',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-callcenter-a');const beforePersonnel=await storage.getAll('personnel');const beforeRecord=await storage.get('recruitment_cases','recruitment-case-004');storage.revokeRoleBeforeNextReadwrite('persona-callcenter-a','role-onboarding-supervisor');await expect(service.startRecruitmentTraining('recruitment-case-004',1,{firstName:'نازنین',lastName:'رضایی',startDate:'2026-08-27',unitId:'unit-sales',positionId:'position-seller',branchUnitId:'unit-branch-central',managerPersonnelId:'personnel-callcenter-a',createAccount:false})).rejects.toThrow('دسترسی یا محدوده');expect(await storage.getAll('personnel')).toEqual(beforePersonnel);expect(await storage.get('recruitment_cases','recruitment-case-004')).toEqual(beforeRecord);});

  it('rejects training when the assigned onboarding role template becomes inactive but another recruitment role remains',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-callcenter-a');const beforeRecord=await storage.get<OperationalRecord>('recruitment_cases','recruitment-case-004'),beforePersonnel=await storage.getAll('personnel'),beforeUsers=await storage.getAll('users'),beforeHistory=await storage.getAll('workflow_history');storage.deactivateRoleBeforeNextReadwrite('role-onboarding-supervisor');await expect(service.startRecruitmentTraining('recruitment-case-004',1,{firstName:'نازنین',lastName:'رضایی',startDate:'2026-08-27',unitId:'unit-sales',positionId:'position-seller',branchUnitId:'unit-branch-central',managerPersonnelId:'personnel-callcenter-a',createAccount:false})).rejects.toThrow('نقش تخصصی فعال مرحله جاری');expect(await storage.get<OperationalRecord>('recruitment_cases','recruitment-case-004')).toEqual(beforeRecord);expect(await storage.getAll('personnel')).toEqual(beforePersonnel);expect(await storage.getAll('users')).toEqual(beforeUsers);expect(await storage.getAll('workflow_history')).toEqual(beforeHistory);});

  it('does not assign the next recruitment stage to a user whose role template became inactive',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-hr-operator');const before=await storage.get<OperationalRecord>('recruitment_cases','recruitment-case-001');storage.deactivateRoleBeforeNextReadwrite('role-recruitment-manager');await expect(service.transitionRecruitmentCase('recruitment-case-001','recruitment-case.hr_review')).rejects.toThrow('مسئول واجد شرایط');expect(await storage.get<OperationalRecord>('recruitment_cases','recruitment-case-001')).toEqual(before);expect((await storage.get<LocalUser>('users','persona-hr-manager'))?.roleIds).toContain('role-recruitment-manager');});

  it('rejects a current recruitment stage actor when its retained role id points to an inactive template',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-hr-operator');const beforeRecord=await storage.get<OperationalRecord>('recruitment_cases','recruitment-case-001'),beforeHistory=await storage.getAll('workflow_history'),beforeAudits=await storage.getAll('audit_events');storage.deactivateRoleBeforeNextReadwrite('role-recruitment-operator');await expect(service.transitionRecruitmentCase('recruitment-case-001','recruitment-case.hr_review')).rejects.toThrow('نقش تخصصی فعال مرحله جاری');expect(await storage.get<OperationalRecord>('recruitment_cases','recruitment-case-001')).toEqual(beforeRecord);expect(await storage.getAll('workflow_history')).toEqual(beforeHistory);expect(await storage.getAll('audit_events')).toEqual(beforeAudits);});

  it('blocks training on a continuity hold even for admin and leaves every dependent store unchanged',async()=>{const{storage,session,service}=await setup();const held=(await storage.get<OperationalRecord>('recruitment_cases','recruitment-case-004'))!;await storage.put('recruitment_cases',{...held,payload:{...held.payload,needsReassignment:true,previousAssigneeUserId:'persona-callcenter-a'}});await login(storage,session,'persona-product-owner');const beforeRecord=await storage.get('recruitment_cases',held.id),beforePersonnel=await storage.getAll('personnel'),beforeUsers=await storage.getAll('users'),beforeHistory=await storage.getAll('workflow_history');await expect(service.startRecruitmentTraining(held.id,held.version,{firstName:'نازنین',lastName:'رضایی',startDate:'2026-08-27',unitId:'unit-sales',positionId:'position-seller',branchUnitId:'unit-branch-central',createAccount:false})).rejects.toThrow('تعیین همه مسئولان');expect(await storage.get('recruitment_cases',held.id)).toEqual(beforeRecord);expect(await storage.getAll('personnel')).toEqual(beforePersonnel);expect(await storage.getAll('users')).toEqual(beforeUsers);expect(await storage.getAll('workflow_history')).toEqual(beforeHistory);});

  it('rejects stale-session and out-of-scope training targets without creating personnel',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-callcenter-a');const input={firstName:'نازنین',lastName:'رضایی',startDate:'2026-08-27',unitId:'unit-sales',positionId:'position-seller',branchUnitId:'unit-branch-central',managerPersonnelId:'personnel-callcenter-a',createAccount:false};const before=await storage.getAll('personnel');storage.switchSessionBeforeNextReadwrite('persona-product-owner');await expect(service.startRecruitmentTraining('recruitment-case-004',1,input)).rejects.toThrow('نشست کاربری هم‌زمان تغییر کرده');expect(await storage.getAll('personnel')).toEqual(before);
    const second=await setup();await login(second.storage,second.session,'persona-callcenter-a');const beforeSecond=await second.storage.getAll('personnel');await expect(second.service.startRecruitmentTraining('recruitment-case-004',1,{...input,unitId:'unit-management',positionId:'position-specialist'})).rejects.toThrow('خارج از محدوده');expect(await second.storage.getAll('personnel')).toEqual(beforeSecond);
    const third=await setup();await login(third.storage,third.session,'persona-callcenter-a');const unit=(await third.storage.get<{companyId?:string}>('organizational_units','unit-sales'))!;await third.storage.put('organizational_units',{...unit,id:'unit-sales',companyId:'company-other'});const beforeThird=await third.storage.getAll('personnel');await expect(third.service.startRecruitmentTraining('recruitment-case-004',1,input)).rejects.toThrow('شرکت');expect(await third.storage.getAll('personnel')).toEqual(beforeThird);});

  it('creates a linked new opportunity from a rejected candidate without rewriting the old dossier',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-hr-operator');const before=await storage.get<{id:string;version:number;status:string;payload:Record<string,unknown>}>('recruitment_cases','recruitment-case-006');const state=await service.reuseRecruitmentCandidate({sourceRecordId:'recruitment-case-006',title:'بررسی مجدد مهسا قربانی برای ارتباط با مشتری',description:'نیاز تازه واحد مدیریت',unitId:'unit-management',branchUnitId:'unit-branch-central',positionTitle:'کارشناس ارتباط با مشتری',employmentType:'تمام‌وقت',requestReason:'سابقه مناسب مصاحبه و نیاز جدید سازمان'});const oldRecord=await storage.get<{id:string;version:number;status:string;payload:Record<string,unknown>}>('recruitment_cases','recruitment-case-006');expect(oldRecord).toEqual(before);const created=state.operationalRecords.find((item)=>item.payload.sourceCandidateRecordId==='recruitment-case-006')!;expect(created).toMatchObject({moduleId:'recruitment-case',status:'submitted',unitId:'unit-management',branchUnitId:'unit-branch-central'});expect(created.payload).toMatchObject({candidateName:'مهسا قربانی',candidateMobile:'09121230061',candidateNationalId:'0081234561',positionTitle:'کارشناس ارتباط با مشتری',requestChannel:'بانک متقاضیان',sourceCandidateTrackingCode:'REC-1404-006'});expect(state.operationalHistory.some((item)=>item.recordId===created.id&&item.eventType==='created')).toBe(true);await expect(service.reuseRecruitmentCandidate({sourceRecordId:'recruitment-case-006',title:'فرصت تکراری',description:'',unitId:'unit-management',branchUnitId:'unit-branch-central',positionTitle:'کارشناس ارتباط با مشتری',employmentType:'تمام‌وقت',requestReason:'ثبت دوباره همان فرصت فعال'})).rejects.toThrow('یک فرصت فعال');});

  it('does not let a unit requester reuse sensitive candidate dossiers',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-seller');await expect(service.reuseRecruitmentCandidate({sourceRecordId:'recruitment-case-006',title:'استفاده خارج از منابع انسانی',description:'',unitId:'unit-sales',branchUnitId:'unit-branch-central',positionTitle:'فروشنده',employmentType:'تمام‌وقت',requestReason:'تلاش برای دسترسی مستقیم به بانک متقاضیان'})).rejects.toThrow('فقط برای منابع انسانی');});

  it('fails closed when the recruitment role is revoked immediately before reuse is written',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-hr-operator');const beforeRecords=await storage.getAll<OperationalRecord>('recruitment_cases');const beforeHistory=await storage.getAll<OperationalRecordHistory>('workflow_history');storage.revokeRoleBeforeNextReadwrite('persona-hr-operator','role-recruitment-operator');await expect(service.reuseRecruitmentCandidate({sourceRecordId:'recruitment-case-006',title:'فرصت هم‌زمان نامجاز',description:'',unitId:'unit-management',branchUnitId:'unit-branch-central',positionTitle:'کارشناس ارتباط با مشتری',employmentType:'تمام‌وقت',requestReason:'آزمون لغو هم‌زمان نقش کارشناس جذب'})).rejects.toThrow('فقط برای منابع انسانی');expect(await storage.getAll<OperationalRecord>('recruitment_cases')).toEqual(beforeRecords);expect(await storage.getAll<OperationalRecordHistory>('workflow_history')).toEqual(beforeHistory);});

  it('lets only the unit manager create for own unit and routes directly to HR without a draft',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-seller');const state=await service.createRecruitmentRequest({title:'نیاز به فروشنده جدید',description:'افزایش ظرفیت فروش',unitId:'unit-sales',branchUnitId:'unit-branch-central',positionTitle:'فروشنده',requestedHeadcount:'2',employmentType:'تمام‌وقت',neededDate:'2026-09-10',salaryRangeRial:'300000000',requestReason:'تکمیل ظرفیت تیم فروش'});const created=state.operationalRecords.find((item)=>item.moduleId==='recruitment-case'&&item.title==='نیاز به فروشنده جدید')!;expect(created.status).toBe('submitted');expect(created.assigneeUserId).toBe('persona-hr-operator');await expect(service.createRecruitmentRequest({...{title:'نیاز غیرمجاز',description:'',unitId:'unit-accounting',branchUnitId:'unit-branch-central',positionTitle:'حسابدار',requestedHeadcount:'1',employmentType:'تمام‌وقت',requestReason:'نیاز واحد دیگر'}})).rejects.toThrow('مدیر فقط می‌تواند');});

  it('derives a sales manager multi-branch scope from active paths and blocks every outside branch',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-seller');let state=await service.loadState();const scope=resolveWorkforceRequestScope(state);expect(scope.source).toBe('active_sales_structure');expect(scope.branchUnitIds).toEqual(expect.arrayContaining(['unit-branch-central','unit-branch-poonak']));expect(scope.seniorSupervisorPersonnelIds).toEqual(expect.arrayContaining(['personnel-sales-senior','personnel-sales-senior-poonak']));const arman=state.personnel.find((item)=>item.id==='personnel-arman')!;const vice=state.personnel.find((item)=>item.id==='personnel-sales-vice')!;const seniorCentral=state.personnel.find((item)=>item.id==='personnel-sales-senior')!;const seniorPoonak=state.personnel.find((item)=>item.id==='personnel-sales-senior-poonak')!;expect(managedSalesBranchIdsForPersonnel(state,arman)).toEqual(['unit-branch-central','unit-branch-poonak']);expect(managedSalesBranchIdsForPersonnel(state,vice)).toEqual(['unit-branch-central','unit-branch-poonak']);expect(managedSalesBranchIdsForPersonnel(state,seniorCentral)).toEqual(['unit-branch-central']);expect(managedSalesBranchIdsForPersonnel(state,seniorPoonak)).toEqual(['unit-branch-poonak']);state=await service.createRecruitmentRequest({title:'فروشنده شعبه پونک',description:'',unitId:'unit-sales',branchUnitId:'unit-branch-poonak',positionTitle:'فروشنده',requestedHeadcount:'1',employmentType:'تمام‌وقت',requestReason:'تکمیل ظرفیت شعبه پونک'});const created=state.operationalRecords.find((item)=>item.title==='فروشنده شعبه پونک')!;expect(created.branchUnitId).toBe('unit-branch-poonak');expect(created.payload.managerialStructureIds).toEqual(['sales-structure-poonak-a']);expect(created.payload.managerialSeniorSupervisorPersonnelIds).toEqual(['personnel-sales-senior-poonak']);await expect(service.createRecruitmentRequest({title:'فروشنده شعبه آزادی',description:'',unitId:'unit-sales',branchUnitId:'unit-branch-azadi',positionTitle:'فروشنده',requestedHeadcount:'1',employmentType:'تمام‌وقت',requestReason:'تکمیل ظرفیت شعبه آزادی'})).rejects.toThrow('حوزه مدیریت فعال');});

  it('removes an inactive sales path branch from every workforce-request choice',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-seller');const path=(await storage.get<SalesStructure>('sales_structures','sales-structure-poonak-a'))!;await storage.put('sales_structures',{...path,status:'inactive'});const state=await service.loadState();const scope=resolveWorkforceRequestScope(state);const arman=state.personnel.find((item)=>item.id==='personnel-arman')!;expect(scope.branchUnitIds).toContain('unit-branch-central');expect(scope.branchUnitIds).not.toContain('unit-branch-poonak');expect(managedSalesBranchIdsForPersonnel(state,arman)).toEqual(['unit-branch-central']);await expect(service.createRecruitmentRequest({title:'درخواست روی مسیر غیرفعال',description:'',unitId:'unit-sales',branchUnitId:'unit-branch-poonak',positionTitle:'فروشنده',requestedHeadcount:'1',employmentType:'تمام‌وقت',requestReason:'این شعبه دیگر مسیر فعال مدیریتی ندارد'})).rejects.toThrow('حوزه مدیریت فعال');});

  it('moves the five QA dossiers through the responsible role cartables',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-hr-operator');let state=await service.transitionRecruitmentCase('recruitment-case-001','recruitment-case.hr_review');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-001')?.status).toBe('hr_review');await login(storage,session,'persona-hr-manager');state=await service.transitionRecruitmentCase('recruitment-case-001','recruitment-case.ready_to_publish');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-001')?.assigneeUserId).toBe('persona-hr-operator');await login(storage,session,'persona-hr-operator');state=await service.transitionRecruitmentCase('recruitment-case-002','recruitment-case.interview_scheduled');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-002')?.assigneeUserId).toBe('persona-seller');await login(storage,session,'persona-callcenter-a');state=await service.transitionRecruitmentCase('recruitment-case-003','recruitment-case.evaluated');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-003')?.status).toBe('evaluated');state=await service.startRecruitmentTraining('recruitment-case-004',1,{firstName:'نازنین',lastName:'رضایی',startDate:'2026-08-27',unitId:'unit-sales',positionId:'position-seller',branchUnitId:'unit-branch-central',managerPersonnelId:'personnel-callcenter-a',createAccount:false});expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-004')?.status).toBe('training');state=await service.transitionRecruitmentCase('recruitment-case-005','recruitment-case.contracted','عملکرد دوره آموزشی تأیید و قرارداد فعال شد');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-005')?.status).toBe('contracted');});
});

describe('candidate resume and documents',()=>{
  const profile=(name='متقاضی رزومه')=>({
    fullName:name,mobile:'09121234567',nationalId:'1234567891',email:'candidate@example.test',city:'تهران',
    unitId:'unit-human-resources',branchUnitId:'unit-branch-central',positionTitle:'کارشناس منابع انسانی',
    educationLevel:'کارشناسی',educationField:'مدیریت',workExperienceYears:'3',lastJobTitle:'کارشناس اداری',
    skills:'اکسل، ارتباطات سازمانی و گزارش‌نویسی',about:'سه سال سابقه مرتبط دارم و برای همکاری بلندمدت آماده هستم.',
    consent:true,files:[{kind:'resume' as const,fileName:'resume.pdf',mimeType:'application/pdf',size:5,dataUrl:'data:application/pdf;base64,JVBERi0='}],
  });

  it('accepts a public form and stores raw resume outside projected state, history and audit',async()=>{
    const{storage,service}=await setup();
    const result=await service.submitRecruitmentApplication(profile());
    const rawRecords=await storage.getAll<OperationalRecord>('recruitment_cases');
    const record=rawRecords.find((item)=>item.trackingCode===result.trackingCode)!;
    const files=await storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files');
    expect(record).toMatchObject({status:'candidate_review',assigneeUserId:'persona-hr-operator'});
    expect(record.payload).toMatchObject({candidateName:'متقاضی رزومه',resumeStatus:'فرم و فایل رزومه تکمیل‌شده',candidateProfileChannel:'applicant'});
    expect(files.filter((item)=>item.recordId===record.id)).toHaveLength(1);
    expect(files.find((item)=>item.recordId===record.id)?.dataUrl).toContain('JVBERi0=');
    const state=await service.loadState();
    expect(JSON.stringify(state)).not.toContain('JVBERi0=');
    expect(JSON.stringify(state.operationalHistory.filter((item)=>item.recordId===record.id))).not.toContain('09121234567');
    expect(JSON.stringify(state.audits.filter((item)=>item.metadata?.recordId===record.id))).not.toContain('1234567891');
    await expect(service.exportSnapshot()).rejects.toThrow('فقط پشتیبان رمزگذاری‌شده');
  });

  it('lets HR edit the form and replaces a resume without deleting the prior version',async()=>{
    const{storage,session,service}=await setup();
    const submitted=await service.submitRecruitmentApplication(profile());
    await login(storage,session,'persona-hr-operator');
    let state=await service.loadState();
    const record=state.operationalRecords.find((item)=>item.trackingCode===submitted.trackingCode)!;
    state=await service.updateRecruitmentCandidateProfile(record.id,record.version,{...profile('متقاضی ویرایش‌شده'),files:[{kind:'resume',fileName:'resume-v2.pdf',mimeType:'application/pdf',size:5,dataUrl:'data:application/pdf;base64,JVBERi0='}]});
    const updated=state.operationalRecords.find((item)=>item.id===record.id)!;
    const files=(await storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files')).filter((item)=>item.recordId===record.id&&item.kind==='resume');
    expect(updated.payload.candidateName).toBe('متقاضی ویرایش‌شده');
    expect(files).toHaveLength(2);
    expect(files.map((item)=>item.status).sort()).toEqual(['active','replaced']);
    const active=files.find((item)=>item.status==='active')!;
    expect((await service.getRecruitmentCandidateFile(record.id,active.id)).fileName).toBe('resume-v2.pdf');
    await expect(service.updateRecruitmentCandidateProfile(record.id,record.version,{...profile('ویرایش قدیمی'),files:[]})).rejects.toThrow('پنجره دیگری');
    expect((await storage.get<OperationalRecord>('recruitment_cases',record.id))?.payload.candidateName).toBe('متقاضی ویرایش‌شده');
  });

  it('revalidates the active session for every authenticated candidate mutation before writing',async()=>{
    for(const operation of ['create','update','reuse'] as const){
      const{storage,session,service}=await setup();let record:OperationalRecord|undefined;
      if(operation==='update'){const submitted=await service.submitRecruitmentApplication({...profile(`نشست ${operation}`),files:[]});record=(await storage.getAll<OperationalRecord>('recruitment_cases')).find((item)=>item.trackingCode===submitted.trackingCode)!;}
      await login(storage,session,'persona-hr-operator');const beforeRecords=await storage.getAll<OperationalRecord>('recruitment_cases'),beforeFiles=await storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files'),beforePersonnel=await storage.getAll<PersonnelRecord>('personnel');storage.switchSessionBeforeNextReadwrite('persona-product-owner');
      const action=operation==='create'
        ?service.createRecruitmentCandidateProfile({...profile('ثبت نشست منقضی'),files:[]})
        :operation==='update'
          ?service.updateRecruitmentCandidateProfile(record!.id,record!.version,{...profile('ویرایش نشست منقضی'),files:[]})
          :service.reuseRecruitmentCandidate({sourceRecordId:'recruitment-case-006',title:'فرصت نشست منقضی',description:'',unitId:'unit-management',branchUnitId:'unit-branch-central',positionTitle:'کارشناس ارتباط',employmentType:'تمام‌وقت',requestReason:'آزمون نشست منقضی در استفاده مجدد'});
      await expect(action).rejects.toThrow('نشست کاربری هم‌زمان تغییر کرده');expect(await storage.getAll<OperationalRecord>('recruitment_cases')).toEqual(beforeRecords);expect(await storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files')).toEqual(beforeFiles);expect(await storage.getAll<PersonnelRecord>('personnel')).toEqual(beforePersonnel);
    }
  });

  it('treats an assigned but inactive recruitment role as no authority for every authenticated candidate mutation',async()=>{
    for(const operation of ['create','update','reuse'] as const){
      const{storage,session,service}=await setup();let record:OperationalRecord|undefined;
      if(operation==='update'){const submitted=await service.submitRecruitmentApplication({...profile(`نقش غیرفعال ${operation}`),files:[]});record=(await storage.getAll<OperationalRecord>('recruitment_cases')).find((item)=>item.trackingCode===submitted.trackingCode)!;}
      await login(storage,session,'persona-hr-operator');
      const beforeRecords=await storage.getAll<OperationalRecord>('recruitment_cases'),beforeFiles=await storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files');
      storage.deactivateRoleBeforeNextReadwrite('role-recruitment-operator');
      const action=operation==='create'
        ?service.createRecruitmentCandidateProfile({...profile('ثبت با نقش غیرفعال'),files:[]})
        :operation==='update'
          ?service.updateRecruitmentCandidateProfile(record!.id,record!.version,{...profile('ویرایش با نقش غیرفعال'),files:[]})
          :service.reuseRecruitmentCandidate({sourceRecordId:'recruitment-case-006',title:'فرصت با نقش غیرفعال',description:'',unitId:'unit-management',branchUnitId:'unit-branch-central',positionTitle:'کارشناس ارتباط',employmentType:'تمام‌وقت',requestReason:'آزمون نقش تخصصی غیرفعال در بانک متقاضیان'});
      await expect(action).rejects.toThrow();
      expect(await storage.getAll<OperationalRecord>('recruitment_cases')).toEqual(beforeRecords);
      expect(await storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files')).toEqual(beforeFiles);
      const rawUser=(await storage.get<LocalUser>('users','persona-hr-operator'))!;
      expect(rawUser.roleIds).toContain('role-recruitment-operator');
      expect((await storage.get<SecurityRole>('security_roles','role-recruitment-operator'))?.status).toBe('inactive');
    }
  });

  it('rejects an inactive recruitment queue role for assignment and file access',async()=>{
    const{storage,service}=await setup();
    const beforeRecords=await storage.getAll<OperationalRecord>('recruitment_cases'),beforeFiles=await storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files');
    storage.deactivateRoleBeforeNextReadwrite('role-recruitment-operator');
    await expect(service.submitRecruitmentApplication({...profile('صف غیرفعال'),files:[]})).rejects.toThrow('کارشناس جذب');
    expect(await storage.getAll<OperationalRecord>('recruitment_cases')).toEqual(beforeRecords);
    expect(await storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files')).toEqual(beforeFiles);

    const second=await setup();const submitted=await second.service.submitRecruitmentApplication(profile('دسترسی فایل نقش غیرفعال'));
    const record=(await second.storage.getAll<OperationalRecord>('recruitment_cases')).find((item)=>item.trackingCode===submitted.trackingCode)!;
    const file=(await second.storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files')).find((item)=>item.recordId===record.id)!;
    await login(second.storage,second.session,'persona-hr-operator');
    const role=(await second.storage.get<SecurityRole>('security_roles','role-recruitment-operator'))!;
    await second.storage.put('security_roles',{...role,status:'inactive',version:(role.version??1)+1});
    await expect(second.service.getRecruitmentCandidateFile(record.id,file.id)).rejects.toThrow();
  });

  it('keeps held and terminal candidate dossiers immutable through ordinary profile updates',async()=>{
    const{storage,session,service}=await setup();const submitted=await service.submitRecruitmentApplication({...profile('پرونده محافظت‌شده'),files:[]});let record=(await storage.getAll<OperationalRecord>('recruitment_cases')).find((item)=>item.trackingCode===submitted.trackingCode)!;await login(storage,session,'persona-hr-operator');
    const held={...record,payload:{...record.payload,needsReassignment:true,previousAssigneeUserId:record.assigneeUserId??'persona-hr-operator'}};await storage.put('recruitment_cases',held);let beforeRecord:OperationalRecord=structuredClone(held),beforeFiles=await storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files');await expect(service.updateRecruitmentCandidateProfile(held.id,held.version,{...profile('ویرایش توقف‌شده'),files:[{kind:'resume',fileName:'blocked.pdf',mimeType:'application/pdf',size:5,dataUrl:'data:application/pdf;base64,JVBERi0='}]})).rejects.toThrow('تعیین همه مسئولان');expect(await storage.get('recruitment_cases',held.id)).toEqual(beforeRecord);expect(await storage.getAll('recruitment_candidate_files')).toEqual(beforeFiles);
    record={...held,status:'rejected',payload:{...held.payload,needsReassignment:false,previousAssigneeUserId:null}};await storage.put('recruitment_cases',record);beforeRecord=structuredClone(record);beforeFiles=await storage.getAll('recruitment_candidate_files');await expect(service.updateRecruitmentCandidateProfile(record.id,record.version,{...profile('ویرایش پرونده نهایی'),files:[]})).rejects.toThrow('پرونده نهایی');expect(await storage.get('recruitment_cases',record.id)).toEqual(beforeRecord);expect(await storage.getAll('recruitment_candidate_files')).toEqual(beforeFiles);
  });

  it('rejects cross-company target organization for create, update and reuse',async()=>{
    const createCase=await setup();await login(createCase.storage,createCase.session,'persona-hr-operator');const hrUnit=(await createCase.storage.get<Record<string,unknown>>('organizational_units','unit-human-resources'))!;await createCase.storage.put('organizational_units',{...hrUnit,companyId:'company-other'});await expect(createCase.service.createRecruitmentCandidateProfile({...profile('ثبت شرکت دیگر'),files:[]})).rejects.toThrow('شرکت');
    const updateCase=await setup();const submitted=await updateCase.service.submitRecruitmentApplication({...profile('ویرایش شرکت دیگر'),files:[]});const candidate=(await updateCase.storage.getAll<OperationalRecord>('recruitment_cases')).find((item)=>item.trackingCode===submitted.trackingCode)!;await login(updateCase.storage,updateCase.session,'persona-hr-operator');const management=(await updateCase.storage.get<Record<string,unknown>>('organizational_units','unit-management'))!;await updateCase.storage.put('organizational_units',{...management,companyId:'company-other'});await expect(updateCase.service.updateRecruitmentCandidateProfile(candidate.id,candidate.version,{...profile('مقصد شرکت دیگر'),unitId:'unit-management',files:[]})).rejects.toThrow('شرکت');
    const reuseCase=await setup();await login(reuseCase.storage,reuseCase.session,'persona-hr-operator');reuseCase.storage.changeUnitCompanyBeforeNextReadwrite('unit-management','company-other');await expect(reuseCase.service.reuseRecruitmentCandidate({sourceRecordId:'recruitment-case-006',title:'فرصت شرکت دیگر',description:'',unitId:'unit-management',branchUnitId:'unit-branch-central',positionTitle:'کارشناس ارتباط',employmentType:'تمام‌وقت',requestReason:'آزمون مقصد شرکت دیگر در استفاده مجدد'})).rejects.toThrow('شرکت');
  });

  it('links a repeated national ID to the prior dossier without merging or overwriting it',async()=>{
    const{storage,service}=await setup();
    const first=await service.submitRecruitmentApplication({...profile('متقاضی سابق'),files:[]});
    const firstRecord=(await storage.getAll<OperationalRecord>('recruitment_cases')).find((item)=>item.trackingCode===first.trackingCode)!;
    const second=await service.submitRecruitmentApplication({...profile('متقاضی فرصت تازه'),mobile:'09121234568',files:[]});
    const records=await storage.getAll<OperationalRecord>('recruitment_cases');
    const secondRecord=records.find((item)=>item.trackingCode===second.trackingCode)!;
    expect(await storage.get<OperationalRecord>('recruitment_cases',firstRecord.id)).toEqual(firstRecord);
    expect(secondRecord.id).not.toBe(firstRecord.id);
    expect(secondRecord.payload.sourceCandidateRecordId).toBe(firstRecord.id);
  });

  it('does not expose applicant dossiers or raw files to an unrelated employee',async()=>{
    const{storage,session,service}=await setup();
    const submitted=await service.submitRecruitmentApplication(profile());
    const record=(await storage.getAll<OperationalRecord>('recruitment_cases')).find((item)=>item.trackingCode===submitted.trackingCode)!;
    const file=(await storage.getAll<RecruitmentCandidateFile>('recruitment_candidate_files')).find((item)=>item.recordId===record.id)!;
    await login(storage,session,'persona-seller');
    expect((await service.loadState()).operationalRecords.some((item)=>item.id===record.id)).toBe(false);
    await expect(service.getRecruitmentCandidateFile(record.id,file.id)).rejects.toThrow('پیدا نشد');
  });
});
