import {describe, expect, it} from 'vitest';
import type {FoundationSession, FoundationStoreName, SalesStructure, SnapshotManifest} from './model';
import {FOUNDATION_STORES} from './model';
import {createSeedData} from './seed';
import {LocalFoundationService} from './service';
import type {StorageAdapter, StorageTransaction} from './storage';
import {managedSalesBranchIdsForPersonnel, resolveWorkforceRequestScope} from './salesManagementScope';

class MemoryStorage implements StorageAdapter {
  private stores = new Map<FoundationStoreName, Map<IDBValidKey, unknown>>(FOUNDATION_STORES.map((store)=>[store,new Map()]));
  async transaction<T>(stores: FoundationStoreName[], _mode: IDBTransactionMode, work: (transaction: StorageTransaction)=>Promise<T>): Promise<T> {const tx:StorageTransaction={get:async<V>(store,id)=>this.stores.get(store)?.get(id) as V|undefined,getAll:async<V>(store)=>[...(this.stores.get(store)?.values()??[])] as V[],put:async<V>(store,value)=>{this.stores.get(store)!.set((value as {id:IDBValidKey}).id,structuredClone(value));},delete:async(store,id)=>{this.stores.get(store)!.delete(id);},clear:async(store)=>{this.stores.get(store)!.clear();}};return work(tx);}
  get<T>(store:FoundationStoreName,id:IDBValidKey){return this.transaction([store],'readonly',(tx)=>tx.get<T>(store,id));}
  getAll<T>(store:FoundationStoreName){return this.transaction([store],'readonly',(tx)=>tx.getAll<T>(store));}
  put<T>(store:FoundationStoreName,value:T){return this.transaction([store],'readwrite',(tx)=>tx.put(store,value));}
  delete(store:FoundationStoreName,id:IDBValidKey){return this.transaction([store],'readwrite',(tx)=>tx.delete(store,id));}
  async replaceAll(stores:Record<FoundationStoreName,unknown[]>){for(const store of FOUNDATION_STORES){this.stores.get(store)!.clear();for(const value of stores[store])this.stores.get(store)!.set((value as {id:IDBValidKey}).id,structuredClone(value));}}
  async exportSnapshot():Promise<SnapshotManifest>{throw new Error('not used');} async importSnapshot():Promise<void>{throw new Error('not used');}
}

async function setup(){const storage=new MemoryStorage();await storage.replaceAll(createSeedData());const session=(await storage.get<FoundationSession>('sessions','active-session'))!;return{storage,session,service:new LocalFoundationService(storage)};}
const login=(storage:MemoryStorage,session:FoundationSession,activeUserId:string)=>storage.put('sessions',{...session,activeUserId,actingAdminUserId:undefined});

describe('recruitment lifecycle',()=>{
  it('blocks the generic recruitment creator and non-assigned stage actors',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-seller');await expect(service.createOperationalRecord('recruitment-case',{title:'دورزدن مسیر اختصاصی',unitId:'unit-sales',branchUnitId:'unit-branch-central'})).rejects.toThrow('مسیر اختصاصی');await expect(service.transitionOperationalRecord('recruitment-case','recruitment-case-001','recruitment-case.hr_review')).rejects.toThrow('مسئول ثبت‌شده');});

  it('seeds five complete deterministic dossiers in different workflow stages',async()=>{const{service}=await setup();const state=await service.loadState();const records=state.operationalRecords.filter((item)=>item.moduleId==='recruitment-case');expect(records).toHaveLength(5);expect(new Set(records.map((item)=>item.status)).size).toBe(5);expect(records.every((item)=>item.payload.currentWaitingFor&&item.workflowVersion===1)).toBe(true);});

  it('lets only the unit manager create for own unit and routes directly to HR without a draft',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-seller');let state=await service.createRecruitmentRequest({title:'نیاز به فروشنده جدید',description:'افزایش ظرفیت فروش',unitId:'unit-sales',branchUnitId:'unit-branch-central',positionTitle:'فروشنده',requestedHeadcount:'2',employmentType:'تمام‌وقت',neededDate:'2026-09-10',salaryRangeRial:'300000000',requestReason:'تکمیل ظرفیت تیم فروش'});const created=state.operationalRecords.find((item)=>item.moduleId==='recruitment-case'&&item.title==='نیاز به فروشنده جدید')!;expect(created.status).toBe('submitted');expect(created.assigneeUserId).toBe('persona-hr-operator');await expect(service.createRecruitmentRequest({...{title:'نیاز غیرمجاز',description:'',unitId:'unit-accounting',branchUnitId:'unit-branch-central',positionTitle:'حسابدار',requestedHeadcount:'1',employmentType:'تمام‌وقت',requestReason:'نیاز واحد دیگر'}})).rejects.toThrow('مدیر فقط می‌تواند');});

  it('derives a sales manager multi-branch scope from active paths and blocks every outside branch',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-seller');let state=await service.loadState();const scope=resolveWorkforceRequestScope(state);expect(scope.source).toBe('active_sales_structure');expect(scope.branchUnitIds).toEqual(expect.arrayContaining(['unit-branch-central','unit-branch-poonak']));expect(scope.seniorSupervisorPersonnelIds).toEqual(expect.arrayContaining(['personnel-sales-senior','personnel-sales-senior-poonak']));const arman=state.personnel.find((item)=>item.id==='personnel-arman')!;const vice=state.personnel.find((item)=>item.id==='personnel-sales-vice')!;const seniorCentral=state.personnel.find((item)=>item.id==='personnel-sales-senior')!;const seniorPoonak=state.personnel.find((item)=>item.id==='personnel-sales-senior-poonak')!;expect(managedSalesBranchIdsForPersonnel(state,arman)).toEqual(['unit-branch-central','unit-branch-poonak']);expect(managedSalesBranchIdsForPersonnel(state,vice)).toEqual(['unit-branch-central','unit-branch-poonak']);expect(managedSalesBranchIdsForPersonnel(state,seniorCentral)).toEqual(['unit-branch-central']);expect(managedSalesBranchIdsForPersonnel(state,seniorPoonak)).toEqual(['unit-branch-poonak']);state=await service.createRecruitmentRequest({title:'فروشنده شعبه پونک',description:'',unitId:'unit-sales',branchUnitId:'unit-branch-poonak',positionTitle:'فروشنده',requestedHeadcount:'1',employmentType:'تمام‌وقت',requestReason:'تکمیل ظرفیت شعبه پونک'});const created=state.operationalRecords.find((item)=>item.title==='فروشنده شعبه پونک')!;expect(created.branchUnitId).toBe('unit-branch-poonak');expect(created.payload.managerialStructureIds).toEqual(['sales-structure-poonak-a']);expect(created.payload.managerialSeniorSupervisorPersonnelIds).toEqual(['personnel-sales-senior-poonak']);await expect(service.createRecruitmentRequest({title:'فروشنده شعبه آزادی',description:'',unitId:'unit-sales',branchUnitId:'unit-branch-azadi',positionTitle:'فروشنده',requestedHeadcount:'1',employmentType:'تمام‌وقت',requestReason:'تکمیل ظرفیت شعبه آزادی'})).rejects.toThrow('حوزه مدیریت فعال');});

  it('removes an inactive sales path branch from every workforce-request choice',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-seller');const path=(await storage.get<SalesStructure>('sales_structures','sales-structure-poonak-a'))!;await storage.put('sales_structures',{...path,status:'inactive'});const state=await service.loadState();const scope=resolveWorkforceRequestScope(state);const arman=state.personnel.find((item)=>item.id==='personnel-arman')!;expect(scope.branchUnitIds).toContain('unit-branch-central');expect(scope.branchUnitIds).not.toContain('unit-branch-poonak');expect(managedSalesBranchIdsForPersonnel(state,arman)).toEqual(['unit-branch-central']);await expect(service.createRecruitmentRequest({title:'درخواست روی مسیر غیرفعال',description:'',unitId:'unit-sales',branchUnitId:'unit-branch-poonak',positionTitle:'فروشنده',requestedHeadcount:'1',employmentType:'تمام‌وقت',requestReason:'این شعبه دیگر مسیر فعال مدیریتی ندارد'})).rejects.toThrow('حوزه مدیریت فعال');});

  it('moves the five QA dossiers through the responsible role cartables',async()=>{const{storage,session,service}=await setup();await login(storage,session,'persona-hr-operator');let state=await service.transitionOperationalRecord('recruitment-case','recruitment-case-001','recruitment-case.hr_review');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-001')?.status).toBe('hr_review');await login(storage,session,'persona-hr-manager');state=await service.transitionOperationalRecord('recruitment-case','recruitment-case-001','recruitment-case.ready_to_publish');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-001')?.assigneeUserId).toBe('persona-hr-operator');await login(storage,session,'persona-hr-operator');state=await service.transitionOperationalRecord('recruitment-case','recruitment-case-002','recruitment-case.interview_scheduled');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-002')?.assigneeUserId).toBe('persona-seller');await login(storage,session,'persona-callcenter-a');state=await service.transitionOperationalRecord('recruitment-case','recruitment-case-003','recruitment-case.evaluated');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-003')?.status).toBe('evaluated');state=await service.transitionOperationalRecord('recruitment-case','recruitment-case-004','recruitment-case.training');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-004')?.status).toBe('training');state=await service.transitionOperationalRecord('recruitment-case','recruitment-case-005','recruitment-case.contracted','عملکرد دوره آموزشی تأیید و قرارداد فعال شد');expect(state.operationalRecords.find((item)=>item.id==='recruitment-case-005')?.status).toBe('contracted');});
});
