import {useMemo, useState, type ReactNode} from 'react';
import {BadgeCheck, Building2, CircleAlert, Crown, Headphones, LockKeyhole, Pencil, Plus, Power, Search, UsersRound, X} from 'lucide-react';
import {can} from './authorization';
import {FormValidationSummary, OptionalLabel, RequiredLabel, validateRequired} from './FormValidation';
import type {FoundationState, PersonnelRecord, SalesHierarchyLevel, SalesStructure} from './model';
import type {LocalFoundationService, SalesStructureInput} from './service';
import type {FoundationExecutor} from './OrganizationPages';
import {salesStructureHasAssignmentHistory, salesStructureSupervisorName} from './salesStructureIdentity';

interface Props {state: FoundationState; service: LocalFoundationService; execute: FoundationExecutor;}

export function SalesStructuresPage({state, service, execute}: Props) {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState<'all'|'active'|'inactive'>('all');
  const [creating, setCreating] = useState(false);
  const [editing, setEditing] = useState<SalesStructure | null>(null);
  const mayManage = can(state.activeUser, 'organization.personnel.manage');
  const rows = useMemo(() => state.salesStructures.filter((item) => {
    const branch = state.units.find((unit) => unit.id === item.branchUnitId)?.name ?? '';
    const names = [item.salesVicePersonnelId, item.salesManagerPersonnelId, item.seniorSupervisorPersonnelId, item.callCenterSupervisorPersonnelId].map((id) => personnelName(state.personnel, id)).join(' ');
    const text = `${item.code} ${branch} ${names}`.toLocaleLowerCase('fa');
    return (status === 'all' || item.status === status) && text.includes(query.trim().toLocaleLowerCase('fa'));
  }), [state, query, status]);

  return <div className="page-stack sales-structures-page">
    <section className="page-intro org-page-intro"><span className="page-intro-icon"><Crown size={24}/></span><div><span>سازمان / ساختار فروش</span><h2>مسیرهای سرپرستان کال‌سنتر</h2><p>مسیر تا پیش از اولین انتساب قابل ویرایش است؛ پس از انتساب برای حفظ تاریخچه قفل می‌شود.</p></div>{mayManage && <div className="page-intro-action"><button className="org-primary-action" onClick={() => setCreating(true)}><Plus size={18}/> ساخت مسیر جدید</button></div>}</section>
    <section className="org-metrics personnel-metrics"><Metric value={state.units.filter((item) => item.type === 'شعبه' && item.status === 'active').length} label="شعبه فعال" icon={<Building2 size={19}/>}/><Metric value={state.salesStructures.filter((item) => item.status === 'active').length} label="مسیر فعال" icon={<Headphones size={19}/>}/><Metric value={state.personnel.filter((item) => item.employmentStatus === 'active' && item.salesHierarchyLevel === 'seller').length} label="فروشنده فعال" icon={<UsersRound size={19}/>}/><Metric value={state.salesStructures.filter((item) => item.status === 'inactive').length} label="ساختار بایگانی" icon={<CircleAlert size={19}/>}/></section>
    <section className="org-panel">
      <div className="sales-structure-toolbar"><label className="search-box"><Search size={18}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="جست‌وجوی شعبه یا نام سرپرست…"/></label><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} aria-label="وضعیت ساختار"><option value="all">همه وضعیت‌ها</option><option value="active">فعال</option><option value="inactive">غیرفعال</option></select></div>
      <div className="sales-structure-list"><div className="sales-structure-list-head"><span>ردیف</span><span aria-hidden="true"/><span>مسیر فروش</span><span>زنجیره سرپرستی و انتساب</span><span>اقدام‌ها</span></div>{rows.map((item) => {const label = salesStructureSupervisorName(item, state.personnel); return <StructureRow key={item.id} item={item} state={state} mayManage={mayManage} onEdit={() => setEditing(item)} onStatus={(next) => {if (next === 'inactive' && !window.confirm(`مسیر سرپرست کال‌سنتر «${label}» غیرفعال شود؟ از این پس در انتخاب فروشنده نمایش داده نمی‌شود.`)) return; void execute('sales-structure-status', () => service.setSalesStructureStatus(item.id, next), `مسیر سرپرست کال‌سنتر «${label}» ${next === 'active' ? 'فعال' : 'غیرفعال'} شد.`);}}/>;})}{!rows.length && <div className="empty-state"><Headphones size={28}/><strong>ساختاری با این مشخصات پیدا نشد.</strong></div>}</div>
    </section>
    {creating && <SalesStructureDialog state={state} onClose={() => setCreating(false)} onSubmit={(input) => void execute('sales-structure-create', () => service.createSalesStructure(input), 'مسیر فروش جدید ایجاد شد.').then((succeeded) => {if (succeeded) setCreating(false);})}/>}
    {editing && <SalesStructureDialog structure={editing} state={state} onClose={() => setEditing(null)} onSubmit={(input) => void execute('sales-structure-update', () => service.updateSalesStructure(editing.id, input), 'مسیر فروش ویرایش شد.').then((succeeded) => {if (succeeded) setEditing(null);})}/>}
  </div>;
}

function StructureRow({item, state, mayManage, onEdit, onStatus}: {item: SalesStructure; state: FoundationState; mayManage: boolean; onEdit: () => void; onStatus: (status: 'active'|'inactive') => void}) {
  const branch = state.units.find((unit) => unit.id === item.branchUnitId)?.name ?? 'شعبه نامشخص';
  const sellers = state.personnel.filter((person) => person.employmentStatus === 'active' && person.salesStructureId === item.id).length;
  const editingLocked = salesStructureHasAssignmentHistory(item.id, state.personnel);
  const editLabel = editingLocked ? 'ویرایش قفل است؛ این مسیر سابقه انتساب پرسنل دارد' : 'ویرایش مسیر فروش';
  return <article className={`sales-structure-row ${item.status === 'inactive' ? 'sales-structure-row--inactive' : ''}`}><span className="sales-structure-icon"><Headphones size={20}/></span><div className="sales-structure-main"><div><strong>{salesStructureSupervisorName(item, state.personnel)}</strong><span className={`status-badge status-badge--${item.status}`}>{item.status === 'active' ? 'فعال' : 'غیرفعال'}</span></div><small>{item.code} · {branch} · نسخه {item.version.toLocaleString('en-US')}</small></div><div className="sales-structure-chain"><span><b>معاونت فروش</b>{personnelName(state.personnel, item.salesVicePersonnelId)}</span><span><b>مدیر فروش</b>{personnelName(state.personnel, item.salesManagerPersonnelId)}</span><span><b>سرپرست ارشد</b>{personnelName(state.personnel, item.seniorSupervisorPersonnelId)}</span><span><b>سرپرست کال‌سنتر</b>{personnelName(state.personnel, item.callCenterSupervisorPersonnelId)}</span><span><b>فروشندگان فعال</b>{sellers.toLocaleString('en-US')} نفر</span></div>{mayManage && <div className="sales-structure-actions"><button className="icon-action icon-action--primary" type="button" aria-label={editLabel} data-tooltip={editLabel} disabled={editingLocked} onClick={onEdit}>{editingLocked ? <LockKeyhole size={16}/> : <Pencil size={16}/>}</button><button className={`icon-action ${item.status === 'active' ? 'icon-action--danger' : 'icon-action--success'}`} type="button" aria-label={item.status === 'active' ? 'غیرفعال‌سازی ساختار' : 'فعال‌سازی ساختار'} data-tooltip={item.status === 'active' ? 'غیرفعال‌سازی ساختار' : 'فعال‌سازی ساختار'} onClick={() => onStatus(item.status === 'active' ? 'inactive' : 'active')}><Power size={17}/></button></div>}</article>;
}

function SalesStructureDialog({structure, state, onClose, onSubmit}: {structure?: SalesStructure; state: FoundationState; onClose: () => void; onSubmit: (input: SalesStructureInput) => void}) {
  const [form, setForm] = useState<SalesStructureInput>(structure ? {branchUnitId: structure.branchUnitId, salesVicePersonnelId: structure.salesVicePersonnelId ?? '', salesManagerPersonnelId: structure.salesManagerPersonnelId, seniorSupervisorPersonnelId: structure.seniorSupervisorPersonnelId, callCenterSupervisorPersonnelId: structure.callCenterSupervisorPersonnelId} : {branchUnitId: '', salesVicePersonnelId: '', salesManagerPersonnelId: '', seniorSupervisorPersonnelId: '', callCenterSupervisorPersonnelId: ''});
  const [errors, setErrors] = useState<string[]>([]);
  const people = (level: SalesHierarchyLevel) => state.personnel.filter((item) => item.employmentStatus === 'active' && item.salesHierarchyLevel === level);
  const submit = () => {const next = validateRequired([{label: 'شعبه', value: form.branchUnitId}, {label: 'معاونت فروش', value: form.salesVicePersonnelId}, {label: 'مدیر فروش', value: form.salesManagerPersonnelId}, {label: 'سرپرست ارشد', value: form.seniorSupervisorPersonnelId}, {label: 'سرپرست کال‌سنتر', value: form.callCenterSupervisorPersonnelId}]); setErrors(next); if (!next.length) onSubmit(form);};
  const select = (label: string, key: keyof SalesStructureInput, level: SalesHierarchyLevel, required = true) => <Field label={label} required={required}><select aria-required={required} value={String(form[key] ?? '')} onChange={(event) => setForm({...form, [key]: event.target.value})}><option value="">انتخاب کنید</option>{people(level).map((person) => <option key={person.id} value={person.id}>{person.firstName} {person.lastName}</option>)}</select></Field>;
  return <div className="modal-layer" role="dialog" aria-modal="true"><button className="modal-scrim" aria-label="بستن" onClick={onClose}/><section className="modal-card"><div className="modal-heading"><div><span>{structure ? 'ویرایش مسیر بدون سابقه انتساب' : 'نسخه جدید ساختار فروش'}</span><h2>{structure ? 'ویرایش مسیر سرپرست کال‌سنتر' : 'ساخت مسیر سرپرست کال‌سنتر'}</h2><p>{structure ? 'تا پیش از اولین انتساب می‌توانید شعبه و زنجیره سرپرستی این مسیر را اصلاح کنید.' : 'نام سرپرست کال‌سنتر، عنوان همین مسیر است؛ ساختار قبلی تغییر نمی‌کند و سابقه قابل ممیزی می‌ماند.'}</p></div><button className="icon-button" onClick={onClose} aria-label="بستن"><X size={20}/></button></div><FormValidationSummary errors={errors}/><div className="org-form-grid personnel-form-grid sales-structure-form-grid"><Field label="شعبه" required full><select aria-required="true" value={form.branchUnitId} onChange={(event) => setForm({...form, branchUnitId: event.target.value})}><option value="">انتخاب شعبه فعال</option>{state.units.filter((item) => item.type === 'شعبه' && item.status === 'active').map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></Field>{select('معاونت فروش', 'salesVicePersonnelId', 'sales_vice')}{select('مدیر فروش', 'salesManagerPersonnelId', 'sales_manager')}{select('سرپرست ارشد', 'seniorSupervisorPersonnelId', 'senior_supervisor')}{select('سرپرست کال‌سنتر', 'callCenterSupervisorPersonnelId', 'sales_supervisor')}</div><div className="dialog-actions"><button className="button button--secondary" onClick={onClose}>انصراف</button><button className="button button--primary" onClick={submit}><BadgeCheck size={17}/> {structure ? 'ذخیره تغییرات' : 'ایجاد مسیر فعال'}</button></div></section></div>;
}

function personnelName(personnel: PersonnelRecord[], id?: string) {const person = personnel.find((item) => item.id === id); return person ? `${person.firstName} ${person.lastName}` : 'تعیین نشده';}
function Metric({value, label, icon}: {value: number; label: string; icon: ReactNode}) {return <article><span>{icon}</span><div><strong>{value.toLocaleString('en-US')}</strong><b>{label}</b><small>ساختار محلی و قابل ممیزی</small></div></article>;}
function Field({label, required = false, full = false, children}: {label: string; required?: boolean; full?: boolean; children: ReactNode}) {return <label className={`field-label ${full ? 'field-label--full' : ''}`}>{required ? <RequiredLabel>{label}</RequiredLabel> : <OptionalLabel>{label}</OptionalLabel>}{children}</label>;}
