import AxeBuilder from '@axe-core/playwright';
import {expect,test,type Page} from '@playwright/test';

async function enterAsAdmin(page:Page){await page.goto('/?page=letters');await page.waitForLoadState('domcontentloaded');const login=page.getByRole('heading',{name:'خوش آمدید'});if(await login.isVisible({timeout:3_000})){await page.getByPlaceholder('username').fill('admin');await page.locator('input[autocomplete="current-password"]').fill('Tapra2@123');await page.getByRole('button',{name:'ورود به سامانه'}).click();}const defer=page.getByRole('button',{name:/وارد می‌شوم/}).first();try{await defer.waitFor({state:'visible',timeout:15_000});await defer.click();await defer.waitFor({state:'hidden',timeout:15_000});}catch{/* پرونده کامل است. */}await page.goto('/?page=letters');await expect(page.getByRole('heading',{name:'نامه‌نگاری سازمانی'})).toBeVisible({timeout:15_000});}

test('نمونه‌های وارده، ارسالی، پیش‌نویس و در جریان پس از بازخوانی باقی می‌مانند',async({page})=>{
  test.setTimeout(60_000);await enterAsAdmin(page);
  await expect(page.locator('.letter-row').filter({hasText:'ابلاغ برنامه قطعی نگهداری شبکه بانکی'})).toBeVisible();
  await page.getByRole('button',{name:/ارسالی و در جریان/}).click();await expect(page.locator('.letter-row').filter({hasText:'درخواست تمدید قرارداد خدمات پشتیبانی'})).toContainText('ارسال‌شده');
  await expect(page.locator('.letter-row').filter({hasText:'ابلاغ برنامه قطعی نگهداری شبکه بانکی'})).toHaveCount(0);
  await expect(page.locator('.letter-row').filter({hasText:'پاسخ تأییدشده به درخواست تأمین‌کننده'})).toContainText('مجوز ارسال صادر شده');
  await page.getByRole('button',{name:/پیش‌نویس‌ها/}).click();await expect(page.locator('.letter-row').filter({hasText:'پیش‌نویس دستورالعمل بایگانی قراردادها'})).toBeVisible();
  await page.getByRole('button',{name:/صف بازبینی/}).click();const review=page.locator('.letter-row').filter({hasText:'پاسخ پیشنهادی به استعلام اداره مالیات'});await expect(review).toContainText('در حال بازبینی');await review.click();
  const detail=page.getByRole('dialog',{name:/نامه LTR-1405-0005/});await expect(detail.locator('.letter-history > div')).toHaveCount(2);await detail.getByRole('button',{name:'بستن'}).first().click();
  await page.reload();await page.getByRole('button',{name:/صف بازبینی/}).click();await expect(page.locator('.letter-row').filter({hasText:'پاسخ پیشنهادی به استعلام اداره مالیات'})).toBeVisible();
});

test('فهرست گیرندگان فقط پرسنل واحدهای مقصد انتخاب‌شده را نشان می‌دهد',async({page})=>{
  await enterAsAdmin(page);await page.getByRole('button',{name:'نامه جدید'}).click();const dialog=page.getByRole('dialog',{name:'ثبت نامه جدید'});const people=dialog.getByRole('group',{name:'گیرندگان مشخص از واحدهای انتخاب‌شده (اختیاری)'});
  await expect(people).toContainText('ابتدا یک یا چند واحد مقصد را انتخاب کنید');await expect(people).not.toContainText('مهدی رضایی');
  const financeUnit=dialog.locator('.letter-unit-picker label').filter({hasText:'خزانه'});await financeUnit.getByRole('checkbox').check();await expect(people).toContainText('مهدی رضایی');await expect(people).toContainText('نیلوفر کریمی');await expect(people).not.toContainText('نازنین اکبری');
  await people.getByRole('checkbox',{name:/مهدی رضایی/}).check();await financeUnit.getByRole('checkbox').uncheck();await expect(people).not.toContainText('مهدی رضایی');
  await financeUnit.getByRole('checkbox').check();await expect(people.getByRole('checkbox',{name:/مهدی رضایی/})).not.toBeChecked();await dialog.getByRole('button',{name:'انصراف'}).click();
});

test('نامه صادره با پیوست به‌صورت پیش‌نویس ثبت و برای بازبینی ارسال می‌شود',async({page})=>{
  test.setTimeout(60_000);await enterAsAdmin(page);await page.getByRole('button',{name:'نامه جدید'}).click();const dialog=page.getByRole('dialog',{name:'ثبت نامه جدید'});await dialog.getByRole('radio',{name:'صادره'}).click();await dialog.getByLabel('موضوع').fill('درخواست همکاری رسمی');await dialog.getByLabel('گیرنده بیرونی').fill('شرکت نمونه');await dialog.getByLabel('متن نامه').fill('با سلام، درخواست همکاری رسمی جهت بررسی و اعلام نظر ارسال می‌شود.');await dialog.locator('input[type="file"]').setInputFiles({name:'official.txt',mimeType:'text/plain',buffer:Buffer.from('official letter')});await expect(dialog).toContainText('official.txt');await dialog.getByRole('button',{name:'ثبت نامه'}).click();
  await page.getByRole('button',{name:/پیش‌نویس‌ها/}).click();const row=page.locator('.letter-row').filter({hasText:'درخواست همکاری رسمی'});await expect(row).toBeVisible();await row.click();let detail=page.getByRole('dialog',{name:/نامه LTR/});await expect(detail).toContainText('شرکت نمونه');await expect(detail.getByRole('link',{name:/official.txt/})).toBeVisible();await detail.getByRole('button',{name:'ویرایش نامه'}).click();const editor=page.getByRole('dialog',{name:'ویرایش نامه'});await editor.getByLabel('موضوع').fill('درخواست همکاری رسمی ـ ویرایش‌شده');await editor.getByRole('button',{name:'ذخیره ویرایش'}).click();const edited=page.locator('.letter-row').filter({hasText:'درخواست همکاری رسمی ـ ویرایش‌شده'});await expect(edited).toBeVisible();await edited.click();detail=page.getByRole('dialog',{name:/نامه LTR/});await detail.getByRole('button',{name:/ارسال برای بازبینی/}).click();
  await page.getByRole('button',{name:/ارسالی و در جریان/}).click();const submitted=page.locator('.letter-row').filter({hasText:'درخواست همکاری رسمی ـ ویرایش‌شده'});await expect(submitted).toContainText('در حال بازبینی');await page.reload();await page.getByRole('button',{name:/ارسالی و در جریان/}).click();await expect(page.locator('.letter-row').filter({hasText:'درخواست همکاری رسمی ـ ویرایش‌شده'})).toBeVisible();
  await page.setViewportSize({width:390,height:844});expect(await page.locator('body').evaluate((element)=>element.scrollWidth>element.clientWidth+1)).toBe(false);const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21a','wcag21aa']).analyze();expect(results.violations.filter((item)=>item.impact==='serious'||item.impact==='critical'),JSON.stringify(results.violations,null,2)).toEqual([]);
});

test('نسخه رسمی نامه سربرگ شاهراه، مشخصات اداری و قرارداد چاپ A4 دارد',async({page})=>{
  test.setTimeout(60_000);await enterAsAdmin(page);await page.getByRole('button',{name:/ارسالی و در جریان/}).click();const row=page.locator('.letter-row').filter({hasText:'درخواست تمدید قرارداد خدمات پشتیبانی'});await expect(row).toBeVisible();await row.click();const detail=page.getByRole('dialog',{name:/نامه LTR-1405-0002/});const sheet=detail.locator('.letter-print-sheet');await expect(sheet.locator('.shahrah-brand')).toBeVisible();await expect(sheet).toContainText('شماره:');await expect(sheet).toContainText('تاریخ و ساعت:');await expect(sheet).toContainText('از:');await expect(sheet).toContainText('به:');await expect(sheet).toContainText('موضوع:');await expect(sheet).toContainText('ارسال‌کننده و مهر دیجیتال');await expect(sheet).toContainText('گیرنده / واحد مقصد');await expect(detail.getByRole('button',{name:'چاپ / ذخیره PDF'})).toBeVisible();
  await page.emulateMedia({media:'print'});expect(await page.evaluate(()=>matchMedia('print').matches)).toBe(true);const printedSheet=page.locator('.letter-print-sheet');await expect(printedSheet).toBeVisible();const printContract=await printedSheet.evaluate((element)=>{const style=getComputedStyle(element);const watermark=getComputedStyle(element,'::before');const address=getComputedStyle(element.querySelector('.official-letter-address')!);return{position:style.position,height:style.height,overflow:style.overflow,border:address.borderTopStyle,watermark:watermark.backgroundImage,opacity:watermark.opacity};});expect(printContract.position).toBe('fixed');expect(printContract.overflow).toBe('hidden');expect(printContract.border).toBe('none');expect(printContract.watermark).toContain('shahrah-mark-lines');expect(Number(printContract.opacity)).toBeGreaterThan(0);await expect(page.locator('.letter-history')).toBeHidden();let pdf=await page.pdf({printBackground:true,preferCSSPageSize:true,displayHeaderFooter:false});expect(pdf.toString('latin1').match(/\/Type\s*\/Page\b/g)??[]).toHaveLength(1);await page.emulateMedia({media:'screen'});await detail.getByRole('button',{name:'بستن'}).first().click();
  await page.getByRole('button',{name:'نامه جدید'}).click();const composer=page.getByRole('dialog',{name:'ثبت نامه جدید'});await composer.getByRole('radio',{name:'صادره'}).click();await composer.getByLabel('موضوع').fill('نامه بلند آزمایشی تک‌صفحه‌ای');await composer.getByLabel('گیرنده بیرونی').fill('سازمان مقصد');await composer.getByLabel('متن نامه').fill('گزارش تفصیلی عملکرد و اقدامات واحد سازمانی برای ثبت در نامه رسمی.\n'.repeat(160));await composer.getByRole('button',{name:'ثبت نامه'}).click();await page.getByRole('button',{name:/پیش‌نویس‌ها/}).click();const longRow=page.locator('.letter-row').filter({hasText:'نامه بلند آزمایشی تک‌صفحه‌ای'});await expect(longRow).toBeVisible();await longRow.click();await page.emulateMedia({media:'print'});pdf=await page.pdf({printBackground:true,preferCSSPageSize:true,displayHeaderFooter:false});expect(pdf.toString('latin1').match(/\/Type\s*\/Page\b/g)??[]).toHaveLength(1);await page.emulateMedia({media:'screen'});
});
