import React, { useState } from 'react';
import { Promotion, PromotionCoreItem, PromotionItemType, Product, ServiceCatalogItem, User, SystemRole, SystemPermission } from '../types';
import { applyCatalogRevision, isPromotionSellable, validateNonNegativeCatalogNumbers, validateUniqueCatalogCode, withCatalogMetadata } from '../utils/catalog';
import { hasPermission } from '../utils/permissions';
import { storage } from '../utils/storage';
import { logAudit } from '../utils/auditLog';
import { formatPortalMoney, getPortalNowTimestamp, getPortalToday, splitPortalTimestamp } from '../utils/operationalFormat';
import { Pencil, Plus, Tag, Trash2, X } from 'lucide-react';
import { PersianDatePicker } from './PersianDatePicker';

interface PromotionsViewProps {
  promotions: Promotion[]; onUpdatePromotions: (promotions: Promotion[]) => void;
  products: Product[]; services: ServiceCatalogItem[]; currentUser: User | null; roles: SystemRole[];
  effectivePermissions: SystemPermission[] | null; impersonatorAdmin: User | null;
}

const emptyForm={title:'',code:'',startDate:'',endDate:'',basePrice:'0',discountAmount:'0',finalPrice:'0',salespersonDiscountCap:'0',conditions:'',salesNotes:'',status:'active' as Promotion['status'],editReason:''};
const inputClass='min-h-11 rounded-lg border border-[var(--border-strong)] bg-[var(--surface)] px-3 py-2 text-sm text-[var(--text-primary)] placeholder:text-[var(--text-muted)]';

export const PromotionsView:React.FC<PromotionsViewProps>=({promotions,onUpdatePromotions,products,services,currentUser,roles,effectivePermissions,impersonatorAdmin})=>{
  const[form,setForm]=useState(emptyForm);const[coreItems,setCoreItems]=useState<PromotionCoreItem[]>([]);const[itemType,setItemType]=useState<PromotionItemType>('goods');const[itemId,setItemId]=useState('');const[showForm,setShowForm]=useState(false);const[editingId,setEditingId]=useState<string|null>(null);const[error,setError]=useState('');
  const canManage=hasPermission(effectivePermissions,['manage_promotions']);const today=getPortalToday();
  if(!currentUser)return null;if(!canManage)return <div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-6 text-[var(--text-secondary)]">دسترسی مدیریت پروموشن را ندارید.</div>;
  const closeForm=()=>{setForm(emptyForm);setCoreItems([]);setItemId('');setEditingId(null);setShowForm(false);setError('');};
  const startCreate=()=>{closeForm();setShowForm(true);};
  const startEdit=(promotion:Promotion)=>{setEditingId(promotion.id);setCoreItems(promotion.coreItems.map((item)=>({...item})));setForm({title:promotion.title,code:promotion.code,startDate:promotion.startDate||'',endDate:promotion.endDate||'',basePrice:String(promotion.basePrice),discountAmount:String(promotion.discountAmount),finalPrice:String(promotion.finalPrice),salespersonDiscountCap:String(promotion.salespersonDiscountCap||0),conditions:promotion.conditions||'',salesNotes:promotion.salesNotes||'',status:promotion.status,editReason:''});setShowForm(true);setError('');};
  const addCoreItem=()=>{const source=itemType==='goods'?products:services;const found=source.find((item)=>item.id===itemId);if(!found)return;const existingIndex=coreItems.findIndex((item)=>item.itemType===itemType&&item.itemId===itemId);if(existingIndex>=0){setCoreItems(coreItems.map((item,index)=>index===existingIndex?{...item,quantity:item.quantity+1}:item));}else{setCoreItems([...coreItems,{itemType,itemId,itemName:found.name,quantity:1}]);}setItemId('');};
  const updateQuantity=(index:number,value:number)=>setCoreItems(coreItems.map((item,i)=>i===index?{...item,quantity:Math.max(1,value||1)}:item));
  const handleSave=()=>{
    if(!hasPermission(effectivePermissions,['manage_promotions'])){setError('مجوز مدیریت پروموشن را ندارید.');return;}if(!form.title.trim()){setError('عنوان پروموشن الزامی است.');return;}const codeError=validateUniqueCatalogCode(promotions,form.code,editingId||undefined);if(codeError){setError(codeError);return;}if(coreItems.length===0){setError('حداقل یک کالا یا خدمت الزامی است.');return;}if(form.startDate&&form.endDate&&form.startDate>form.endDate){setError('تاریخ پایان نمی‌تواند قبل از تاریخ شروع باشد.');return;}
    const numbers={basePrice:Number(form.basePrice),discountAmount:Number(form.discountAmount),finalPrice:Number(form.finalPrice),salespersonDiscountCap:Number(form.salespersonDiscountCap)};const numberError=validateNonNegativeCatalogNumbers(numbers);if(numberError){setError(numberError);return;}
    if(!editingId){const created:Promotion=withCatalogMetadata({id:`promo_${Date.now()}`,code:form.code.trim(),title:form.title.trim(),version:1,startDate:form.startDate||undefined,endDate:form.endDate||undefined,coreItems:coreItems.map((item)=>({...item})),basePrice:numbers.basePrice,discountAmount:numbers.discountAmount,finalPrice:numbers.finalPrice,salespersonDiscountCap:numbers.salespersonDiscountCap||undefined,status:form.status,conditions:form.conditions.trim()||undefined,salesNotes:form.salesNotes.trim()||undefined,createdAt:getPortalNowTimestamp(),createdByUserId:currentUser.id,createdByUserName:currentUser.fullName});const updated=[created,...promotions];storage.savePromotions(updated);logAudit({action:'promotion_created',effectiveUser:currentUser,impersonatorAdmin,roles,permissionUsed:'manage_promotions',targetId:created.id,details:`${created.code} — ${created.title} — قیمت نهایی ${created.finalPrice}`});onUpdatePromotions(updated);closeForm();return;}
    const existing=promotions.find((item)=>item.id===editingId);if(!existing){setError('پروموشن پیدا نشد.');return;}const revision=applyCatalogRevision({existing:withCatalogMetadata(existing),actor:currentUser,reason:form.editReason,changedAt:getPortalNowTimestamp(),patch:{code:form.code.trim(),title:form.title.trim(),startDate:form.startDate||undefined,endDate:form.endDate||undefined,coreItems:coreItems.map((item)=>({...item})),basePrice:numbers.basePrice,discountAmount:numbers.discountAmount,finalPrice:numbers.finalPrice,salespersonDiscountCap:numbers.salespersonDiscountCap||undefined,status:form.status,conditions:form.conditions.trim()||undefined,salesNotes:form.salesNotes.trim()||undefined}});if(revision.ok===false){setError(revision.error);return;}const updated=promotions.map((item)=>item.id===editingId?revision.record:item);storage.savePromotions(updated);logAudit({action:'promotion_version_created',effectiveUser:currentUser,impersonatorAdmin,roles,permissionUsed:'manage_promotions',targetId:existing.id,details:`v${revision.record.version}: ${revision.changedFields.join(', ')} — ${form.editReason.trim()}`});onUpdatePromotions(updated);closeForm();
  };
  return <div className="space-y-5" dir="rtl">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-bold text-[var(--text-primary)]"><Tag className="h-5 w-5"/> پروموشن‌ها</h2><p className="mt-1 text-sm text-[var(--text-secondary)]">قیمت نهایی مشتری مستقل از جمع اجزا و تخفیف است؛ تغییر مؤثر نسخه جدید می‌سازد.</p></div><button onClick={startCreate} className="flex min-h-11 items-center gap-1 rounded-lg bg-[var(--primary)] px-4 py-2 text-sm font-bold text-white"><Plus className="h-4 w-4"/> پروموشن جدید</button></header>
    {showForm&&<section className="space-y-4 rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4 shadow-sm"><div className="flex items-center justify-between"><h3 className="font-bold text-[var(--text-primary)]">{editingId?'ویرایش نسخه‌دار پروموشن':'پروموشن جدید'}</h3><button onClick={closeForm} aria-label="بستن"><X className="h-5 w-5 text-[var(--text-secondary)]"/></button></div>
      <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-4"><input className={inputClass} placeholder="عنوان *" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/><input className={inputClass} placeholder="کد *" value={form.code} onChange={(e)=>setForm({...form,code:e.target.value})}/><PersianDatePicker value={form.startDate} onChange={(value)=>setForm({...form,startDate:value})} placeholder="تاریخ شروع"/><PersianDatePicker value={form.endDate} onChange={(value)=>setForm({...form,endDate:value})} placeholder="تاریخ پایان"/>
        <input className={inputClass} type="number" min="0" placeholder="قیمت پایه/ارزش مرجع" value={form.basePrice} onChange={(e)=>setForm({...form,basePrice:e.target.value})}/><input className={inputClass} type="number" min="0" placeholder="مبلغ تخفیف اطلاعاتی" value={form.discountAmount} onChange={(e)=>setForm({...form,discountAmount:e.target.value})}/><input className={inputClass} type="number" min="0" placeholder="قیمت نهایی مستقل مشتری *" value={form.finalPrice} onChange={(e)=>setForm({...form,finalPrice:e.target.value})}/><input className={inputClass} type="number" min="0" placeholder="سقف تخفیف فروشنده" value={form.salespersonDiscountCap} onChange={(e)=>setForm({...form,salespersonDiscountCap:e.target.value})}/>
        <textarea className={`${inputClass} md:col-span-2`} placeholder="شرایط" value={form.conditions} onChange={(e)=>setForm({...form,conditions:e.target.value})}/><textarea className={`${inputClass} md:col-span-2`} placeholder="توضیح مجاز فروش" value={form.salesNotes} onChange={(e)=>setForm({...form,salesNotes:e.target.value})}/><select className={inputClass} value={form.status} onChange={(e)=>setForm({...form,status:e.target.value as Promotion['status']})}><option value="active">فعال</option><option value="inactive">غیرفعال</option><option value="expired">منقضی</option></select>{editingId&&<input className={`${inputClass} md:col-span-2`} placeholder="دلیل ویرایش *" value={form.editReason} onChange={(e)=>setForm({...form,editReason:e.target.value})}/>}
      </div>
      <div className="space-y-2 border-t border-[var(--border)] pt-3"><h4 className="text-sm font-bold text-[var(--text-primary)]">اجزای کالا/خدمت</h4><div className="flex flex-wrap gap-2"><select className={inputClass} value={itemType} onChange={(e)=>{setItemType(e.target.value as PromotionItemType);setItemId('');}}><option value="goods">کالا</option><option value="service">خدمت</option></select><select className={`${inputClass} min-w-[220px]`} value={itemId} onChange={(e)=>setItemId(e.target.value)}><option value="">انتخاب جزء</option>{(itemType==='goods'?products:services).filter((item)=>item.isActive).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><button onClick={addCoreItem} className="min-h-11 rounded-lg bg-[var(--surface-muted)] px-3 text-sm text-[var(--text-primary)]">افزودن ردیف</button></div><div className="space-y-2">{coreItems.map((item,index)=><div key={`${item.itemType}_${item.itemId}`} className="flex flex-wrap items-center gap-2 rounded-lg border border-[var(--border)] bg-[var(--surface-muted)] p-2 text-sm text-[var(--text-primary)]"><span className="flex-1">{item.itemType==='goods'?'کالا':'خدمت'} — {item.itemName}</span><input className={`${inputClass} w-24`} type="number" min="1" value={item.quantity} onChange={(e)=>updateQuantity(index,Number(e.target.value))}/><button onClick={()=>setCoreItems(coreItems.filter((_,i)=>i!==index))} aria-label="حذف ردیف"><Trash2 className="h-4 w-4 text-[var(--danger)]"/></button></div>)}</div></div>
      {error&&<div className="rounded-lg bg-[var(--danger-soft)] p-2 text-sm text-[var(--danger)]">{error}</div>}<button onClick={handleSave} className="min-h-11 rounded-lg bg-[var(--primary)] px-4 py-2 text-sm font-bold text-white">{editingId?'ثبت نسخه جدید':'ثبت پروموشن'}</button>
    </section>}
    <section className="overflow-x-auto rounded-xl border border-[var(--border)] bg-[var(--surface)] p-4 shadow-sm"><table className="w-full min-w-[900px] text-sm"><thead><tr className="border-b border-[var(--border)] text-right text-[var(--text-secondary)]"><th className="p-2">عنوان</th><th className="p-2">کد</th><th className="p-2">اجزا</th><th className="p-2">قیمت نهایی</th><th className="p-2">نسخه/آخرین تغییر</th><th className="p-2">وضعیت فروش</th><th className="p-2">عملیات</th></tr></thead><tbody>{promotions.map((promotion)=>{const sellable=isPromotionSellable(promotion,today);const stamp=splitPortalTimestamp(promotion.updatedAt);const sellableLabel='reason' in sellable?sellable.reason:'قابل فروش';return <tr key={promotion.id} className="border-b border-[var(--border)] text-[var(--text-primary)] hover:bg-[var(--surface-muted)]"><td className="p-2">{promotion.title}</td><td className="p-2 font-mono">{promotion.code}</td><td className="p-2 text-[var(--text-secondary)]">{promotion.coreItems.map((item)=>`${item.itemName} × ${item.quantity}`).join('، ')}</td><td className="p-2">{formatPortalMoney(promotion.finalPrice)}</td><td className="p-2 text-xs text-[var(--text-secondary)]">v{promotion.version||1}{promotion.updatedAt?` — ${stamp.date} ${stamp.time}`:' — اولیه'}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-xs ${sellable.ok?'bg-[var(--success-soft)] text-[var(--success)]':'bg-[var(--danger-soft)] text-[var(--danger)]'}`}>{sellableLabel}</span></td><td className="p-2"><button onClick={()=>startEdit(promotion)} className="flex min-h-11 items-center gap-1 rounded-lg px-3 text-[var(--primary)]"><Pencil className="h-4 w-4"/> ویرایش</button></td></tr>})}</tbody></table></section>
  </div>;
};
