import 'fake-indexeddb/auto';
import {describe,expect,it} from 'vitest';
import {createSeedData} from '../seed';
import {LocalFoundationService} from '../service';
import {IndexedDBAdapter,type StorageAdapter,type StorageTransaction} from '../storage';
import type {AuditEvent,FoundationStoreName,IdempotencyRecord,SnapshotManifest} from '../model';
import type {LegalCaseHistory,LegalDeadline,LegalDocumentMetadata,LegalNotice,LegalProceeding} from './model';

class HookStorage implements StorageAdapter{
  failNextStore?:FoundationStoreName;
  constructor(private readonly base:StorageAdapter){}
  transaction<T>(stores:FoundationStoreName[],mode:IDBTransactionMode,work:(transaction:StorageTransaction)=>Promise<T>):Promise<T>{return this.base.transaction(stores,mode,(tx)=>work({...tx,put:async(store,value)=>{if(this.failNextStore===store){this.failNextStore=undefined;throw new Error('injected operation failure');}return tx.put(store,value);}}));}
  get<T>(store:FoundationStoreName,id:IDBValidKey){return this.base.get<T>(store,id)} getAll<T>(store:FoundationStoreName){return this.base.getAll<T>(store)} put<T>(store:FoundationStoreName,value:T){return this.base.put(store,value)} delete(store:FoundationStoreName,id:IDBValidKey){return this.base.delete(store,id)} replaceAll(stores:Record<FoundationStoreName,unknown[]>){return this.base.replaceAll(stores)} exportSnapshot():Promise<SnapshotManifest>{return this.base.exportSnapshot()} importSnapshot(snapshot:SnapshotManifest){return this.base.importSnapshot(snapshot)}
}

async function setup(){const storage=new IndexedDBAdapter(`tapra-legal-operations-${crypto.randomUUID()}`);await storage.replaceAll(createSeedData());const service=new LocalFoundationService(storage);await service.createLegalEntity({displayName:'شخصیت حقوقی کاملاً مصنوعی OPERATIONS'},'ops-entity');const state=await service.createLegalCase({title:'پرونده کاملاً مصنوعی عملیات',caseType:'رسیدگی آزمایشی',owningLegalEntityId:(await service.loadState()).legalInspection!.legalEntities[0].id,parties:[{kind:'person',displayName:'شاکی مصنوعی مستقل',role:'complainant'},{kind:'person',displayName:'پرداخت‌کننده مصنوعی مستقل',role:'payer'}]},'ops-case');return {storage,service,record:state.legalInspection!.cases[0]};}

describe('legal case operations phase two',()=>{
  it('records a proceeding, notice, deadline and document metadata then reloads them',async()=>{
    const {storage,service,record}=await setup();let state=await service.createLegalProceeding({caseId:record.id,authorityType:'court',authorityName:'شعبه آزمایشی یک',stage:'initial_review',externalReferenceMasked:'REF-***-42'},record.version,'ops-proceeding');const proceeding=state.legalInspection!.proceedings[0];const receivedAt=new Date().toISOString();const dueAt=new Date(Date.now()+86_400_000).toISOString();state=await service.recordLegalNotice({caseId:record.id,proceedingId:proceeding.id,noticeType:'response_required',receivedAt,externalReferenceMasked:'NOTICE-***-7',deadline:{dueAt,priority:'high',assigneeUserId:state.activeUser.id},document:{documentType:'notice',classification:'confidential',displayName:'ابلاغیه مصنوعی نسخه یک',mimeType:'application/pdf',sizeBytes:2048,checksum:'a'.repeat(64)}},proceeding.version,'ops-notice');
    expect(state.legalInspection!.notices).toHaveLength(1);expect(state.legalInspection!.deadlines).toHaveLength(1);expect(state.legalInspection!.documents).toHaveLength(1);expect(state.legalInspection!.history.sort((a,b)=>a.sequence-b.sequence).map((item)=>item.action)).toEqual(['created','proceeding_created','notice_received']);const rawDocument=(await storage.getAll<LegalDocumentMetadata>('legal_document_metadata'))[0];expect(rawDocument).toMatchObject({contentState:'metadata_only',classification:'confidential'});expect(rawDocument).not.toHaveProperty('blob');expect(rawDocument).not.toHaveProperty('dataUrl');expect(rawDocument).not.toHaveProperty('storagePath');
  });

  it('replays commands and transitions each child exactly once with CAS',async()=>{
    const {storage,service,record}=await setup();const input={caseId:record.id,authorityType:'administrative' as const,authorityName:'مرجع مصنوعی',stage:'hearing' as const};let state=await service.createLegalProceeding(input,record.version,'ops-repeat');await service.createLegalProceeding(input,record.version,'ops-repeat');expect(await storage.getAll<LegalProceeding>('legal_proceedings')).toHaveLength(1);const proceeding=state.legalInspection!.proceedings[0];const receivedAt=new Date().toISOString();state=await service.recordLegalNotice({caseId:record.id,proceedingId:proceeding.id,noticeType:'hearing',receivedAt,deadline:{dueAt:new Date(Date.now()+172_800_000).toISOString(),priority:'normal',assigneeUserId:state.activeUser.id}},1,'ops-transition-notice');const notice=state.legalInspection!.notices[0];const deadline=state.legalInspection!.deadlines[0];state=await service.acknowledgeLegalNotice(notice.id,notice.version,'ops-ack');await service.acknowledgeLegalNotice(notice.id,notice.version,'ops-ack');expect(state.legalInspection!.notices[0]).toMatchObject({status:'acknowledged',version:2});state=await service.completeLegalDeadline(deadline.id,deadline.version,'ops-complete');expect(state.legalInspection!.deadlines[0]).toMatchObject({status:'completed',version:2});await expect(service.completeLegalDeadline(deadline.id,deadline.version,'ops-stale')).rejects.toThrow('هم‌زمان');state=await service.closeLegalProceeding(proceeding.id,proceeding.version,'ops-close-proceeding');expect(state.legalInspection!.proceedings[0]).toMatchObject({status:'closed',version:2});await service.setLegalRecordStatus(record.id,record.version,'open','qa_lifecycle','ops-open-case');state=await service.setLegalRecordStatus(record.id,2,'closed','scenario_completed','ops-close-case');expect(state.legalInspection!.cases[0].status).toBe('closed');const historyCount=(await storage.getAll<LegalCaseHistory>('legal_case_history')).length;await service.acknowledgeLegalNotice(notice.id,notice.version,'ops-ack');await service.closeLegalProceeding(proceeding.id,proceeding.version,'ops-close-proceeding');expect(await storage.getAll<LegalCaseHistory>('legal_case_history')).toHaveLength(historyCount);
  });

  it('rolls back the complete notice bundle when audit persistence fails',async()=>{
    const {storage,service,record}=await setup();const state=await service.createLegalProceeding({caseId:record.id,authorityType:'court',authorityName:'شعبه آزمایشی rollback',stage:'initial_review'},record.version,'ops-rollback-proceeding');const proceeding=state.legalInspection!.proceedings[0];const hooked=new HookStorage(storage);hooked.failNextStore='audit_events';await expect(new LocalFoundationService(hooked).recordLegalNotice({caseId:record.id,proceedingId:proceeding.id,noticeType:'other',receivedAt:new Date().toISOString(),deadline:{dueAt:new Date(Date.now()+86_400_000).toISOString(),priority:'critical',assigneeUserId:state.activeUser.id},document:{documentType:'other',classification:'internal',displayName:'سند آزمایشی rollback'}},proceeding.version,'ops-rollback-notice')).rejects.toThrow('injected');expect(await storage.getAll<LegalNotice>('legal_notices')).toEqual([]);expect(await storage.getAll<LegalDeadline>('legal_deadlines')).toEqual([]);expect(await storage.getAll<LegalDocumentMetadata>('legal_document_metadata')).toEqual([]);expect((await storage.getAll<IdempotencyRecord>('idempotency_keys')).some((item)=>item.id==='ops-rollback-notice')).toBe(false);
  });

  it('blocks closing the parent while an operational child remains open',async()=>{
    const {service,record}=await setup();await service.createLegalProceeding({caseId:record.id,authorityType:'court',authorityName:'مرجع باز مصنوعی',stage:'hearing'},record.version,'ops-open-child');await service.setLegalRecordStatus(record.id,record.version,'open','qa_lifecycle','ops-parent-open');await expect(service.setLegalRecordStatus(record.id,2,'closed','scenario_completed','ops-parent-close-blocked')).rejects.toThrow('تعیین تکلیف');
  });

  it('keeps child records out of projection when their dedicated view permission is removed',async()=>{
    const {storage,service,record}=await setup();await service.createLegalProceeding({caseId:record.id,authorityType:'other',authorityName:'مرجع مخفی مصنوعی',stage:'appeal'},record.version,'ops-projection');const role=(await storage.getAll<import('../model').SecurityRole>('security_roles')).find((item)=>item.id==='role-legal-manager')!;await storage.put('security_roles',{...role,permissions:role.permissions.filter((permission)=>permission!=='legal.proceeding.summary.view'),version:role.version+1});const state=await service.loadState();expect(state.legalInspection!.cases).toHaveLength(1);expect(state.legalInspection!.proceedings).toEqual([]);expect(state.audits.filter((item:AuditEvent)=>item.action==='legal.proceeding.created')).toEqual([]);
  });
});
